### ISSUE TITLE
[Crash] Programmable Speaker

### ISSUE THREAD

**Issue by crrepitv** [Team-Immersive-Intelligence/ImmersiveIntelligence#128]
You can,t craft the Programmable Speaker and when you place it in creative the Game/Server crashes

**Environment**
 - Minecraft version:1.12.2
 - Forge version:14.23.5.2847
 - Immersive Intelligence version:0.2.0.1
 - Immersive Engineering version:0.12-98

**Comment by Pabilo8** [comment]
Fixed in 0.2.1

**Comment by Verkleckert2** [comment]
Hello,
we were jus playing our modpack and as my friend placed the programmable speaker the server crashed. 

We are already using version 0.2.1
Minecraft version: 1.12.2
Immersive Engineering version: 0.12-98
