### ISSUE TITLE
Chemical Bath Visual Glitch/ broken 

### ISSUE THREAD

**Issue by Cbingle** [Team-Immersive-Intelligence/ImmersiveIntelligence#132]
**Describe the bug**
Building Chemical Bath : Works
inserting liquid into proper liquid slot as well as item in item slot breaks entire machine at a loss of 1 iron sheetmetal as well as 
the contents that are used as input

**To Reproduce**
1. Build Structure
2. put inputs in 
3. get kicked from the GUI and the visual bug happens 
4. Locked out of structure 

**Expected behavior**
Trying to make treated wood with it since the recipe allowed the use of the chemical bath

12 treated wood to be made

**Screenshots or GIFs**

![2021-09-27_03 49 36](https://user-images.githubusercontent.com/31973043/134866667-67f0a524-655d-4793-bd5d-b2aee4a617b6.png)
where the windmill is connected is where the power port should be
![2021-09-27_03 53 30](https://user-images.githubusercontent.com/31973043/134866986-6c3e675f-6ba2-42fe-9ddb-67fd2c19a77c.png)

**Logs**
Add game logs (logs/latest.log and crash log (if exists) ).

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version:14.23.5.2847
-  Modpack: MC Eternal version 1.5

**Comment by Pabilo8** [comment]
Please try to replicate this issue in 0.2.1, I tried but couldn't get the bug to show.
If it doesn't occur anymore we can close the issue.
