### ISSUE TITLE
[BUG] 0.2.1 crash on startup

### ISSUE THREAD

**Issue by Muglegack** [Team-Immersive-Intelligence/ImmersiveIntelligence#144]
**Launcher Error output**
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Exit Code: 255

**Environment**
 - OS: Ubuntu 20.04.3 LTS
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2855
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
 - Immersive Posts version: 0.2.1
 - Immersive Petroleum version: 1.12.2-1.1.9
 - Immersive Cables version: 1.12.2-1.3.2
 - Buildcraft version: buildcraft-all-7.99.24.8
 - 
 - I play on a custom modified version of FTBrevelation for 1.12.2
 - my mods folder: https://drive.google.com/drive/folders/1HIKXD6igKKA2tKcfZbbRFEqAU0Q1JfNx?usp=sharing

**Logs**
[crash-2022-01-08_18.09.21-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7833660/crash-2022-01-08_18.09.21-client.txt)

I already deleted the config-folder as you said in the description and updated forge but it still crashes. Only if i delete one of these mods it works: immersive intelligence, immersive petroleum or buildcraft... Only had the oroblem after upgrading immersive intelligence to 0.2.1. Before that all three mods worked together just fine.

**Comment by mcclellanja** [comment]
Came here to post this exact same crash, followed the same steps and works when any two of the mods are installed but not all three. Glad I'm not the only one having this issue. Excited to get this update work in my pack! Awesome work.

**Comment by DapperSpoder** [comment]
I have the exact same issue, but it calls out Immersive Posts instead of Buildcraft

**Comment by AlexIIL** [comment]
I should have looked for this issue earlier sorry.

A quick look indicates BuildCraft Lib is loading before immersive intelligence sets up it's structures, so a hacky fix on your side would be to add `before:buildcraftlib` to your `@Mod(dependencies)` declaration - at least that's probably the simplest solution that doesn't require moving either buildcraft's guide logic or II's init logic.

**Comment by LeKripiY** [comment]
Hey, I found the issue, II is incompatible with immersive cables I tested it, I recently downloaded some mods and for once installed immersive cables, when IC and II are both installed it crashes the game idk why.

**Comment by Hawk777** [comment]
@LeKripiY it’s not just Immersive Cables. I don’t have that and get the same crash. I do have Immersive Petroleum and BuildCraft though.

**Comment by LeKripiY** [comment]
@Hawk777  Then it's both, I used only this mod with Immersive Cables and the game wouldn't launch but if you say you only used it with buildcraft then both mods crashes the game. And Muglegack has both that's why it crashes his game.

**Comment by Kerzenmacher** [comment]
I'm getting the same issue in my pack - removing II fixes it, but I'd really like to include this mod in my pack. Has there been any solution as of yet?

**Comment by Hawk777** [comment]
Certainly not an ideal option, but the previous version of II doesn’t have this bug, which is what I’ve stuck to until a proper fix arrives.

**Comment by Kerzenmacher** [comment]
Hmm.. indeed not ideal, considering all the neat new features in the latest version.. but it's better than nothing - thanks =)

**Comment by AlexIIL** [comment]
I think if your pack is large enough *(has more than 1500 items)* setting the buildcraft option `Performance` > `guideItemSearchLimit` to `1500` (the minimum value) should exclude everything that isn't buildcraft from it's guide book.

**Comment by Kerzenmacher** [comment]
Yes, this worked! TYVM <3

**Comment by Muglegack** [comment]
> I should have looked for this issue earlier sorry.
> 
> A quick look indicates BuildCraft Lib is loading before immersive intelligence sets up it's structures, so a hacky fix on your side would be to add `before:buildcraftlib` to your `@Mod(dependencies)` declaration - at least that's probably the simplest solution that doesn't require moving either buildcraft's guide logic or II's init logic.

I'm sorry I have no idea where to add the declaration you mentioned. In the config file?

**Comment by AlexIIL** [comment]
It's in the code - only the developer of the mod could add that.

**Comment by Blueberrypie255** [comment]
> I think if your pack is large enough _(has more than 1500 items)_ setting the buildcraft option `Performance` > `guideItemSearchLimit` to `1500` (the minimum value) should exclude everything that isn't buildcraft from it's guide book.

When I launch the game, I dont see this in the .properties file.

**Comment by Xeladin** [comment]
So does the error: {(java.lang.Error: Failed to create a page link for immersivepetroleum:schematic class flaxbeard.immersivepetroleum.common.items.ItemProjector ({ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"immersivepetroleum:schematic",Count:1b,tag:{multiblock:"II:Packer"},Damage:0s})
at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:114)}
Have a solution or no? Because I'm having the same exact issue, did anyone found out what to do? For what I know, when I removed build craft the game started and played perfectly, but I would really like to have build craft in my server

**Comment by AlexIIL** [comment]
@Xeladin essentially [yes](https://github.com/Pabilo8/ImmersiveIntelligence/issues/144#issuecomment-1051285353):

> I think if your pack is large enough (has more than 1500 items) setting the buildcraft option Performance > guideItemSearchLimit to 1500 (the minimum value) should exclude everything that isn't buildcraft from it's guide book.

**Comment by NostalgicLorikeet** [comment]
I have 0.3.0, the crash still occurs
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/29894500/2b15c919-b66e-470e-8cd0-55f025bcb724)
