### ISSUE TITLE
[BUG] Some mortar bullet crashes the game

### ISSUE THREAD

**Issue by LeKripiY** [Team-Immersive-Intelligence/ImmersiveIntelligence#147]
Depending on which ammo you are using with the mortar can crash your game.

I don't know if there are more ammo that crashes but i used the very last mortar ammo in creative inventory (the high explosive one)

I just heard the sound of the mortar shooting and then it crashed.

using the lastest immersive engineering and intelligence (IE:v0.12-98 ; II:0.2.1)
NOTE: also i was using other IE addons such as Immersive Railroading and maybe i shot toward some IR rail but i used the highest inclinaison (to shoot further) and i may wouldn't have even touched the rail.
also there was a steel chain fence next to the mortar on visual the mortar could shot above the fence but maybe it just shot directly the fence and that would mean if you shoot a block right next to the mortar it crashes the game.

**Comment by Pabilo8** [comment]
May be related to II's previous multiblock destruction code, there were some issues when destroying multiblocks, but they disappeared when the new multiblock loading system was introduced.
