### ISSUE TITLE
[BUG] Engineer's manual kicks the player on a server

### ISSUE THREAD

**Issue by cqundefine** [Team-Immersive-Intelligence/ImmersiveIntelligence#148]
**Describe the bug**
When you are playing multiplayer on a server, and you try to close the Engineer's manual it will kick you from the server with a message that a fatal error occured. It is caused by this addon, as removing it fixed the issue.

**To Reproduce**
1. Create and join a minecraft server with the base mod and this addon
2. Open the Engineer's manual
3. Close it

**Expected behavior**
It should just simply close it and not kick the player.

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: 0.12-98
 - Immersive Engineering version: 0.2.1

**Comment by kappa-maintainer** [comment]
https://github.com/Pabilo8/ImmersiveIntelligence/blob/fb18ad30d300af0306a2a98363eca29a25e3c513/src/main/java/pl/pabilo8/immersiveintelligence/common/network/MessageManualClose.java#L52

**Comment by Kerzenmacher** [comment]
Having the same issue ^^
Was there a solution to this at all?

**Comment by kappa-maintainer** [comment]
> Having the same issue ^^ Was there a solution to this at all?

#158 
You need to compile it yourself, though.

**Comment by Pabilo8** [comment]
Fixed.
