### ISSUE TITLE
ammunition workbench crash[BUG]

### ISSUE THREAD

**Issue by Biviho** [Team-Immersive-Intelligence/ImmersiveIntelligence#151]
**Describe the bug**
Crash during ammunition creation in an ammunition workbench, causing also crash on reload,
Caused by a null pointer exception.

**To Reproduce**
1. create a revolver core (tested with the first type, i don't remember the name)
2. fill a casing with gunpowder
3. input them in an ammo workbench
4. crash
5. reloading the world cause a crash

**Expected behavior**
well, not crashing and getting the bullet

**Logs**
[crash-2022-01-28_21.01.39-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7961601/crash-2022-01-28_21.01.39-client.txt)

**Environment**
 - OS: windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2855
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98

the modlist can be found inside the crashlog, i can add it separately if needed, it's a chonky modpack, but i can test it in a simpler environment

**Comment by Pabilo8** [comment]
Fixed.
