### ISSUE TITLE
[BUG] Flippers crash 0.21

### ISSUE THREAD

**Issue by Vaihacky** [Team-Immersive-Intelligence/ImmersiveIntelligence#152]
**Describe the bug**
As it seems when you upgrade light engineer boots with flippers and then try to sprint in the water the game crashes. 

**Environment**
 - OS: Windows 10 Home
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2855
 - ImmersiveEngineering-core-0.12-98.jar
 - Immersiveintelligence-core-0.2.1.jar
 - Also used immersivepetroleum-1.12.2-1.1.10.jar

**Crash log:**
Short description is "Ticking player"
[crash-2022-02-02_11.31.00-server.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7985163/crash-2022-02-02_11.31.00-server.txt)

**Proof gif:**
![javaw_IZYEU6obLc](https://user-images.githubusercontent.com/98878054/152129386-ac860c53-898d-43b6-8007-af504903407d.gif)

Also the same problem is occurring  with snow rackets but with snow in this case

**Crash log:**
Short description is "Ticking player"
[crash-2022-02-02_11.57.13-server.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/7985320/crash-2022-02-02_11.57.13-server.txt)

**Proof gif:**
![javaw_eIzqZf4PRe](https://user-images.githubusercontent.com/98878054/152132243-0bbe4e95-2947-4792-b2c4-a946c76d389e.gif)

**Comment by Vaihacky** [comment]
I'll try to solve this issue (maybe it's my issue btw) by downloading newer version of forge

**Comment by WarrenOC** [comment]
Have the same issue. After a little bit of digging it seems to be something with the armor's damage value or attribute modifier.

**Comment by supopur** [comment]
Same issue. Btw you did a great job with the giffs and stuff.

**Comment by Pabilo8** [comment]
Fixed.
