### ISSUE TITLE
Engineer's Light Armour invisible when worn

### ISSUE THREAD

**Issue by Taggart1993** [Team-Immersive-Intelligence/ImmersiveIntelligence#154]
**Describe the bug**
When I wear the Engineer's Light Armour, it is invisible in the inventory player widget, in third-person mode, and on player hands. I cannot test if it is invisible to other players. All other armour is visible. Light Armour is visible in hotbar and inventory, but not on player. 

**To Reproduce**

1. install II 0.2.1
2. open inventory and get Engineer's Light Armour of any piece
3. Wear it
4. It's invisible.

**Expected behavior**
Expected behavior is the armour being visible

**Screenshots or GIFs**
Add screenshots of animated GIFs (even better) of the problem (if it is a visual glitch).
![Minecraft 1 12 2 2_6_2022 4_07_15 PM](https://user-images.githubusercontent.com/85570109/152707514-126058c0-93db-4476-a689-304ad46d0bd1.png)

**Logs**
N/A

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
AppleSkin
Client Tweaks
Controlling
CreativeCore
CubicChunks
CubicWorldGen
Dynamic Surroundings
Dynamic View
EnhancedVisuals
GraveStone Mod
Iblis Headshots
Immersive Engineering
Immersive Intelligence
Immersive Petroleum
ItemPhysic Full
JEI Hider
JEI Integration
JER Ore Integration
JourneyMap
JEI
Just Enough Banner Patterns
Just Enough Petroleum
Just Enough Resources
MalisisCore
Matchlock Guns
Medieval Music
Mouse Tweaks
Never Enough Currency
OpenComputers 
OpenFM
OpenLights
OpenPrinter
OpenScreens
Optifine
OreLib
Player Trade (zetal)
PWEM
Rough Tweaks
Sound Filters
Vic's Modern Warfare Mod

**Comment by kappa-maintainer** [comment]
Probably caused by Vic

**Comment by Wr1teErr0r** [comment]
it seems like it is, removing VMW from my game seems to fix it
