### ISSUE TITLE
Filler Multiblock won't form.[BUG]

### ISSUE THREAD

**Issue by smblackwll** [Team-Immersive-Intelligence/ImmersiveIntelligence#156]
**Describe the bug**
The filler multiblock will not form when you follow the instructions in the manual.

**To Reproduce**
1.Build the multiblock
2. Try and recreate
3. 
**Expected behavior**
To build the multiblock

**Comment by ninjadude752** [comment]
Also stacking on here to say the ammunition workshop also doesn't work, so I have no way to produce bullets.

**Comment by Pabilo8** [comment]
This was caused by incorrect block variants (conveyors) being displayed in the manual.
