### ISSUE TITLE
[question/possible bug] crafttweaker method for rotary input

### ISSUE THREAD

**Issue by Biviho** [Team-Immersive-Intelligence/ImmersiveIntelligence#160]
ok, so, i tought i understood what the method wanted as paramethers to create a new rotary input, but it doesn't seems to work, and i have no clue if i'm doing something wrong or there is a bug.
tests are done with mystical mechanics wich provide a mechanical system compatible with better with mods and ember

**To Reproduce**
1. write the function 
import mods.immersiveintelligence.RotaryInput;
RotaryInput.addInput("mysticalmechanics.tileentity.TileEntityAxle", 50);

2. start the game and check that II recognize TileEntityAxle as an existing class
3. build contraption as in the pictures and see that the Windmill work as intended, while the other don't

**Expected behavior**
the wheel on the transmission box connected to the axle is powered

IE Windmill version that work fine

![2022-02-20_18 52 56](https://user-images.githubusercontent.com/57569917/154857822-f367794d-196d-448b-a2ca-c37faef8ee61.png)

mystical mechanics version added with crafttweaker that do nothing

![2022-02-20_18 53 04](https://user-images.githubusercontent.com/57569917/154857842-bb380ffe-a20b-4750-a5c3-12ea3f635b5d.png)

**Environment**
 - OS: windows 10
 - Minecraft version: 1.12.2
 - Forge version:14.23.5.2859
 - Immersive Intelligence version: 0.21
 - Immersive Engineering version: 0.12-98

the modpack is a pretty big modpack and i will do some test also in a smaller modpack environment

**Comment by Pabilo8** [comment]
Sorry it took me so long to respond, I just forgot to add this to the github project.

As of 5272fb7b397e069fc312a0eadd53f8d6e5fd15a6 II rotary power has compatibility with Mystical Mechanics.
