### ISSUE TITLE
[BUG]Breaking the Immersive Intelligence multi-block structure causes the client to close

### ISSUE THREAD

**Issue by sddsd2332** [Team-Immersive-Intelligence/ImmersiveIntelligence#165]
My English is not very good, so this is translated by Google.

**Describe the bug**
Build a multi-block structure Coagulator after installing CubicChunks
Destroy the multi-block structure Coagulator
Client crashes, no crash reports

**To Reproduce**

1. Build a multi-block structure Coagulator after installing CubicChunks
2. Destroy the multi-block structure Coagulator
3. Client crashes, no crash reports

**Logs**
[debug - Compared.log](https://github.com/OpenCubicChunks/CubicChunks/files/8178393/debug.-.Compared.log)
[latest - Compared.log](https://github.com/OpenCubicChunks/CubicChunks/files/8178395/latest.-.Compared.log)

**Environment**
 - OS: w10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2588
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98
 - Other mods:
 - CubicChunks-1.12.2-0.0.1233.0-SNAPSHOT-all.jar
 - CubicWorldGen-1.12.2-0.0.167.0-SNAPSHOT-all.jar
 - immersivepetroleum-1.12.2-1.1.10.jar
 - jei_1.12.2-4.16.1.302.jar
 - journeymap-1.12.2-5.7.1.jar
 - JustEnoughCharacters-1.12.0-3.5.1.jar

See details at #[Crash report on CubicChunks 148 ](https://github.com/OpenCubicChunks/CubicChunks/issues/748)

**Comment by VDeltaGabriel** [comment]
After investigation we can say that it is most likely problem on CubicChunks side.
