### ISSUE TITLE
[BUG] motor belt rendering issue

### ISSUE THREAD

**Issue by LeKripiY** [Team-Immersive-Intelligence/ImmersiveIntelligence#173]
(T̶h̶e̶ f̶l̶a̶t̶ s̶i̶d̶e̶ o̶f̶ m̶o̶t̶o̶r̶ b̶e̶l̶t̶ i̶s̶ a̶l̶w̶a̶y̶s̶ f̶a̶c̶i̶n̶g̶ n̶o̶r̶t̶h̶.)
EDIT: vertical motor belt are always facing WEST

**Comment by LeKripiY** [comment]
As of the latest 0.3.0 build, the bug is still present:
![image](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/77859121/f8805d29-5df8-4c1e-ac3c-8ee6b3fa81b0)

**Comment by Pabilo8** [comment]
Fixed by fa8dbb6
