### ISSUE TITLE
[BUG] Filler: some errors in the manual for the construction

### ISSUE THREAD

**Issue by EnricoH** [Team-Immersive-Intelligence/ImmersiveIntelligence#182]
**Bug/Problem 1**

Description:
- The animated buildpreview shows the wrong type of Conveyor Belt (Covered Conveyor Belt) instead of the normal one, which is required for the multiblock, marked in green.
- Instead of the Sheetmetal Chute there is a Covered Conveyor Belt in the animated buildpreview, marked in red.
- The "Required Materials:" list shows the correct items and amounts needet for the multiblock.

![2022-04-16_20 52 12](https://user-images.githubusercontent.com/7204348/163689074-27c64aab-e7e5-4e34-887f-5665592a4d44.png)
![2022-04-16_19 15 06](https://user-images.githubusercontent.com/7204348/163689076-2bf4cc9c-63e8-4605-b3be-ff3d758fa0e5.png)
![2022-04-16_21 41 53](https://user-images.githubusercontent.com/7204348/163689290-a10e59b9-8df7-4e98-aa5d-0f0d0ff59f77.png)

- I compiled the current source for the II 0.2.2.jar but these bugs are still there.
- Also I want to point out, that all Sheetmetal Chutes are called the same, so its not clear which one to use.

**Environment**
 - OS: Windows 11
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version:  immersiveintelligence-0.2.1.jar
 - Immersive Engineering version: ImmersiveEngineering-0.12-98.jar

**Comment by Pabilo8** [comment]
Fixed by 178d3c2
