### ISSUE TITLE
[BUG] Shooting SMG Crashes the game

### ISSUE THREAD

**Issue by Croat86** [Team-Immersive-Intelligence/ImmersiveIntelligence#210]
**Describe the bug**
I tested the II Items in Creative, when i use the SMG and shoot something with more then 2,3 Bullets, the game freezes and crashes then.

**To Reproduce**
1. Add SMG and SMG Ammo into Inventory
2. Shoot on a Cow or a Spider faster then 2,3 Bullets
3. Game Freezes
4. Crash

**Expected behavior**
A clear description of what you expected to happen.

**Logs**
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/9331030/latest.log)
[ruins_log_dim_2.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/9331031/ruins_log_dim_2.txt)

**Environment**
 - OS: Win10Pro
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: immersiveintelligence-0.2.1.jar
 - Immersive Engineering version: ImmersiveEngineering-0.12-98.jar
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

Xaero's Minimap
xaero96
Xaeros_Minimap_22.12.0_Forge_1.12.jar

Xaero's World Map
xaero96
XaerosWorldMap_1.26.0_Forge_1.12.jar

AE2 Stuff
bdew
ae2stuff-0.7.0.4-mc1.12.2.jar

AE2 Wireless Fluid Terminal
TheRealp455w0rd
WirelessFluidTerminal-1.12.2-1.0.4.jar

AE2 Wireless Interface Terminal
TheRealp455w0rd
WirelessInterfaceTerminal-1.12.2-1.0.2.jar

AE2 Wireless Terminal Library
TheRealp455w0rd
AE2WTLib-1.12.2-1.0.34.jar

AI Improvements
QueenOfMissiles
AIImprovements-1.12-0.0.1b3.jar

AppleCore
squeek502
AppleCore-mc1.12.2-3.4.0.jar

AppleSkin
squeek502
AppleSkin-mc1.12-1.0.14.jar

Applied Energistics 2
AlgorithmX2
appliedenergistics2-rv6-stable-7.jar

AttributeFix
DarkhaxDev
AttributeFix-1.12.2-1.0.4.jar

Baubles
Azanor13
Baubles-1.12-1.5.2.jar

BdLib
bdew
bdlib-1.14.3.12-mc1.12.2.jar

Better Builder's Wands
Portablejim
BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar

Better Foliage
octarine_noise
BetterFoliage-MC1.12-2.3.3.jar

Better Survival mod
block_vader
better_survival-1.4.1.jar

BetterFps
Guichaguri
BetterFps-1.4.8.jar

BiblioCraft
Nuchaz
BiblioCraft[v2.4.6][MC1.12.2].jar

Biomes O' Plenty
Forstride
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar

Bookshelf
DarkhaxDev
Bookshelf-1.12.2-2.3.590.jar

Born in a Barn
Speiger
Born In A Barn V1.8-1.12-1.1.jar

Brandon's Core
brandon3055
BrandonsCore-1.12.2-2.4.20.162-universal.jar

Building Gadgets
Direwolf20
BuildingGadgets-2.8.4.jar

Carry On
Tschipp
carryon-1.12.2-1.12.6.20.jar

CB Multipart
covers1624
ForgeMultipart-1.12.2-2.6.2.83-universal.jar

CC: Tweaked
SquidDev
cc-tweaked-1.12.2-1.89.2.jar

Chameleon
Texelsaur
Chameleon-1.12-4.1.3.jar

Chisel
tterrag1098
Chisel-MC1.12.2-1.0.2.45.jar

Chisels & Bits - For Forge
AlgorithmX2
chiselsandbits-14.33.jar

Click Machine
Shadows_of_Fire
ClickMachine-1.12.2-1.2.0.jar

Clumps
Jaredlll08
Clumps-3.1.2.jar

CodeChicken Lib 1.8.+
covers1624
CodeChickenLib-1.12.2-3.2.3.358-universal.jar

Collective (Forge)
Serilum
collective-1.12.2-3.0.jar

Comforts (Forge)
TheIllusiveC4
comforts-1.12.2-1.4.1.3.jar

ConnectedTexturesMod
tterrag1098
CTM-MC1.12.2-1.0.2.31.jar

Cooking for Blockheads
BlayTheNinth
CookingForBlockheads_1.12.2-6.5.0.jar

CoroUtil
Corosus
coroutil-1.12.1-1.2.37.jar

CraftTweaker
Jaredlll08
CraftTweaker2-1.12-4.1.20.678.jar

Cucumber Library
BlakeBr0
Cucumber-1.12.2-1.1.3.jar

Custom NPCs
Noppes_
CustomNPCs_1.12.2-(05Jul20).jar

Dark Utilities
DarkhaxDev
DarkUtils-1.12.2-1.8.230.jar

Day Zombies
martinbv95
DayZombiez.jar

Decocraft
RazzleberryFox
Decocraft-2.6.3.7_1.12.2.jar

DesirePaths
Corosus
desirepaths-1.12.1-1.2.8.jar

Dynamic Lights
atomicstrykergrumpy
DynamicLights-1.12.2.jar

Dynamic Surroundings
OreCruncher
DynamicSurroundings-1.12.2-3.6.1.0.jar

Enchantment Descriptions
DarkhaxDev
EnchantmentDescriptions-1.12.2-1.1.15.jar

Ender IO
crazypants_mc_the_second
EnderIO-1.12.2-5.3.70.jar

Ender Storage 1.8.+
covers1624
EnderStorage-1.12.2-2.4.6.137-universal.jar

EnderCore
tterrag1098
EnderCore-1.12.2-0.5.76.jar

Energy Converters
xalcon
energyconverters_1.12.2-1.3.7.30.jar

Engineer's Decor
wilechaote
engineersdecor-1.12.2-1.1.5.jar

Engineer's Doors
nihiltres
engineers_doors-1.12.2-0.9.1.jar

Engineer's Tools
wilechaote
engineerstools-1.12.2-1.0.5.jar

Extended Days
SilentChaos512
ExtendedDays-1.12.2-0.2.9-28.jar

ExtraCells2 - SamLam140330's Fork
SamLam140330
ExtraCells-1.12.2-2.6.7.jar

Farming for Blockheads
BlayTheNinth
FarmingForBlockheads_1.12.2-3.1.28.jar

Fast Leaf Decay
olafskiii
FastLeafDecay-v14.jar

FastFurnace
Shadows_of_Fire
FastFurnace-1.12.2-1.3.1.jar

FastWorkbench
Shadows_of_Fire
FastWorkbench-1.12.2-1.7.3.jar

Flux Networks
sonar_sonic
FluxNetworks-1.12.2-4.1.1.34.jar

Foam​Fix
asiekierka
foamfix-0.10.14-1.12.2.jar

ForgeEndertech
EnderLanky
ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar

Future MC
thedarkcolour
future-mc-0.2.11.jar

Game Stages
DarkhaxDev
GameStages-1.12.2-2.0.123.jar

Gas Conduits
pupnewfster
EnderIO-conduits-mekanism-1.12.2-5.3.70.jar

Gauges and Switches
wilechaote
rsgauges-1.12.2-1.2.8.jar

GraveStone Mod
henkelmax
gravestone-1.10.3.jar

Guide-API
TehNut
Guide-API-1.12-2.1.8-63.jar

Horror Elements mod
predator97427fr
Horror Elements mod 1.12.2_7.0.jar

Hwyla
TehNut
Hwyla-1.8.26-B41_1.12.2.jar

ICBM - Classic
QueenOfMissiles
ICBM-classic-1.12.2-4.1.0b20211106011048.jar

iChunUtil
ohaiiChun
iChunUtil-1.12.2-7.2.2.jar

Immersive Cables
SanAndreaP
ImmersiveCables-1.12.2-1.3.2.jar

Immersive Energy
CrimsonDragonRider
Immersive Energy-1.12.2-0.5.5.jar

Immersive Engineering
BluSunrize
ImmersiveEngineering-0.12-98.jar

Immersive Intelligence
Pabilo8
immersiveintelligence-0.2.1.jar

Immersive Petroleum
Flaxbeard
immersivepetroleum-1.12.2-1.1.10.jar

Industrial Craft
sfPlayer1
industrialcraft-2-2.8.170-ex112.jar

Industrial Wires
malte0811
IndustrialWires-1.7-35.jar

Iron Backpacks
gr8pefish
IronBackpacks-1.12.2-3.0.8-12.jar

Iron Jetpacks
BlakeBr0
IronJetpacks-1.12-2-1.1.0.jar

IvToolkit
Ivorforce
IvToolkit-1.3.3-1.12.jar

JEI Integration
SnowShock35
jeiintegration_1.12.2-1.6.0.jar

Just Enough Calculation
towdium
JustEnoughCalculation-1.12.2-3.2.7.jar

Just Enough Energistics (JEE)
TheRealp455w0rd
JustEnoughEnergistics-1.12.2-1.0.8.jar

Just Enough HarvestCraft (JEHC)
mrapplexz
just-enough-harvestcraft-1.12.2-1.7.2.jar

Just Enough Items (JEI)
mezz
jei_1.12.2-4.16.1.301.jar

Just Enough Resources (JER)
way2muchnoise
JustEnoughResources-1.12.2-0.9.2.60.jar

Large Fluid Tank
Kotori316
LargeFluidTank-12.5.3.jar

Large Ore Deposits
EnderLanky
AdLods-1.12.2-1.0.8.0-build.0504.jar

Loadout
mallrat208
Loadout-1.0.2.jar

Lost Books
FatherToast
LostBooks-II-1.12.2-2.0.3.jar

Macaw's Bridges
sketch_macaw
mcw-bridges-1.0.6b-mc1.12.2.jar

Macaw's Doors
sketch_macaw
mcw-doors-1.0.3-mc1.12.2.jar

Macaw's Fences and Walls
sketch_macaw
mcw-fences-1.0.0-mc1.12.2.jar

Macaw's Furniture
sketch_macaw
mcw-furniture-1.0.1-mc1.12.2beta.jar

Macaw's Roofs
sketch_macaw
mcw-roofs-1.0.2-mc1.12.2.jar

Macaw's Trapdoors
sketch_macaw
mcw-trapdoors-1.0.3-mc1.12.2.jar

Macaw's Windows
sketch_macaw
mcw-windows-1.0.0-mc1.12.2.jar

MalisisCore
Ordinastie
malisiscore-1.12.2-6.5.1.jar

MalisisDoors
Ordinastie
malisisdoors-1.12.2-7.3.0.jar

MalisisSwitches
Ordinastie
malisisswitches-1.12.2-5.1.0.jar

MCMultiPart
amadornes
MCMultiPart-2.5.3.jar

Mekanism
bradyaidanc
Mekanism-1.12.2-9.8.3.390.jar

Mekanism Generators
bradyaidanc
MekanismGenerators-1.12.2-9.8.3.390.jar

Mekanism Tools
bradyaidanc
MekanismTools-1.12.2-9.8.3.390.jar

Mo' Bends
IVESIRIS
MoBends_1.12.2-1.2.1-19.12.21.jar

Mob Dismemberment
ohaiiChun
MobDismemberment-1.12.2-7.0.0.jar

Modern Ruins Pack
breengrub2415
Modern_Ruins_Pack_1.12.2.4(chisel).jar

Modular Forcefield System
gaeakat
MFFS-1.12.2-4.0.1.0_1.12_cc3a5aa.jar

Modular Powersuits
machinemuse
ModularPowersuits-1.12.2-1.0.46.jar

Mouse Tweaks
YaLTeR
MouseTweaks-2.10-mc1.12.2.jar

MrCrayfish's Furniture Mod
MrCrayfish
furniture-6.3.2-1.12.2.jar

MrTJPCore
MrTJP
MrTJPCore-1.12.2-2.1.4.43-universal.jar

Mutant Beasts
Chumbanotz
MutantBeasts-1.12.2-1.0.2.jar

Nature's Compass
Chaosyr
NaturesCompass-1.12.2-1.8.5.jar

Neat
Vazkii
Neat 1.4-17.jar

Numina
machinemuse
Numina-1.12.2-1.0.38.jar

Obfuscate
MrCrayfish
obfuscate-0.4.2-1.12.2.jar

OMLib
Keridos
omlib-1.12.2-3.1.5-256.jar

Open Glider
gr8pefish
OpenGlider-1.12.1-1.1.0.jar

Open Modular Passive Defense
Keridos
ompd-1.12.2-3.1.1-76.jar

Open Modular Turrets
Keridos
openmodularturrets-1.12.2-3.1.14-382.jar

OpenBlocks
OpenMods
OpenBlocks-1.12.2-1.8.1.jar

OpenBlocks Elevator
vsngarcia
ElevatorMod-1.12.2-1.3.14.jar

OpenComputers
Sangar_
OpenComputers-MC1.12.2-1.7.5.192.jar

Opencomputers ICBM-Classic Addon
TheEternalSoap
OpenComputersICBMAddon-1.3.jar

OpenModsLib
OpenMods
OpenModsLib-1.12.2-0.12.2.jar

OpenPrinter
MichiyoRavencroft
OpenPrinter-1.12.2-0.1.0.16.jar

OpenScreens
itsmeowdev
openscreens-1.12.2-1.0.1.jar

Oreberries
josephcsible
oreberries-1.12.x-0.5.0.jar

OreLib
OreCruncher
OreLib-1.12.2-3.6.0.1.jar

Orva Alarms and Sirens
Orvngexy
Orva Alarms 2.2 1.12.2.jar

p455w0rd's Library
TheRealp455w0rd
p455w0rdslib-1.12.2-2.3.161.jar

Pam's BrewCraft
pamharvestcraft
Pam's BrewCraft 1.12.2-1.0.2.jar

Pam's Cookables - Pam's Harvestcraft Addon
BloodWorkXGaming
pamscookables-1.1.jar

Pam's Get All the Seeds!
pamharvestcraft
Pam's Get all the Seeds! 1.12a.jar

Pam's HarvestCraft
pamharvestcraft
Pam's HarvestCraft 1.12.2zg.jar

Phosphor (Forge)
jellysquid3_
phosphor-1.12.2-0.2.6+build50-universal.jar

Placebo
Shadows_of_Fire
Placebo-1.12.2-1.6.0.jar

Practical Logistics 2
sonar_sonic
practicallogistics2-1.12.2-3.0.8-11.jar

Project Red - Compat
MrTJP
ProjectRed-1.12.2-4.9.4.120-compat.jar

Project Red - Core
MrTJP
ProjectRed-1.12.2-4.9.4.120-Base.jar

Project Red - Expansion
MrTJP
ProjectRed-1.12.2-4.9.4.120-mechanical.jar

Project Red - Exploration
MrTJP
ProjectRed-1.12.2-4.9.4.120-world.jar

Project Red - Fabrication
MrTJP
ProjectRed-1.12.2-4.9.4.120-fabrication.jar

Project Red - Illumination
MrTJP
ProjectRed-1.12.2-4.9.4.120-lighting.jar

Project Red - Integration
MrTJP
ProjectRed-1.12.2-4.9.4.120-integration.jar

ProjectE
SinKillerJ
ProjectE-1.12.2-PE1.4.1.jar

PTRLib
RazzleberryFox
PTRLib-1.0.5.jar

Recurrent Complex
Ivorforce
RecurrentComplex-1.4.8.2.jar

Redstone Flux
TeamCoFH
RedstoneFlux-1.12-2.1.1.1-universal.jar

Scape And Run: Parasite Vaccine
bullfighter2009
srpvaccine-1.0.0.jar

Scape and Run: Parasites
Dhanantry
SRParasites-1.12.2v1.9.5.jar

Scape and Run: Parasites Addon by NoCube
nocubeyt
NoCubes_SRP_Addon_2.3.1.jar

Set World Spawn Point (Forge)
Serilum
setworldspawnpoint_1.12.2-1.6.jar

Shadowfacts' Forgelin
ShadowfactsDev
Forgelin-1.8.4.jar

Silent Lib (silentlib)
SilentChaos512
SilentLib-1.12.2-3.0.14+168.jar

Simply Light
Flanks255
simplylight-1.12.2-0.8.7.jar

Sonar Core
sonar_sonic
sonarcore-1.12.2-5.0.19-20.jar

SoulBottle
bagu_chan500
soulbottle-1.12.2-1.1.jar

Spiders 2.0
TheCyberBrick
spiders-2.0-1.12.2-1.0.3.jar

Storage Drawers
Texelsaur
StorageDrawers-1.12.2-5.4.2.jar

SuperMartijn642's Config Lib
SuperMartijn642
supermartijn642configlib-1.1.6-forge-mc1.12.jar

SuperMartijn642's Core Lib
SuperMartijn642
supermartijn642corelib-1.0.19-forge-mc1.12.jar

SwingThroughGrass
exidex
stg-1.12.2-1.2.3.jar

Techguns
pWn3d_1337
techguns-1.12.2-2.0.2.0_pre3.2.jar

Tesseract
SuperMartijn642
tesseract-1.0.27-forge-mc1.12.jar

Tetra
mickelus
tetra-1.12.2-0.39.1.jar

Thicc Entities
wiresegal
thiccentities-1.4.jar

Tool Belt
gigaherz
ToolBelt-1.12.2-1.9.14.jar

Torch Bandolier
SilentChaos512
TorchBandolier-1.12.2-0.1.1-4.jar

Torchmaster
xalcon
torchmaster_1.12.2-1.8.5.0.jar

Tree Chopper
MrDuchy
TreeChopper-1.12.2-1.2.4.jar

Tree Harvester (Forge)
Serilum
treeharvester_1.12.2-4.0.jar

Vegan Life
rademax93
veganlife-1.12.2-1.5.0.jar

Wawla - What Are We Looking At
DarkhaxDev
Wawla-1.12.2-2.6.275.jar

Waystones
BlayTheNinth
Waystones_1.12.2-4.1.0.jar

Wireless Crafting Terminal
TheRealp455w0rd
WirelessCraftingTerminal-1.12.2-3.12.97.jar

Wireless Pattern Terminal
TheRealp455w0rd
WirelessPatternTerminal-1.12.2-1.0.3.jar

Wireless Redstone CBE
covers1624
WR-CBE-1.12.2-2.3.2.33-universal.jar

Zombie Awareness
Corosus
zombieawareness-1.12.1-1.11.16.jar

**Comment by Croat86** [comment]
It seems to be the 4th Bullet in the mixed Magazine under @immersiveIngineering which causes the crash.

**Comment by darthvader45** [comment]
Same, mainly with incendiary and explosive rounds.  Though mine causes a hang after the second or third bullet.
