### ISSUE TITLE
[BUG] crashing buildcraft

### ISSUE THREAD

**Issue by soggyfever4568** [Team-Immersive-Intelligence/ImmersiveIntelligence#213]
started crashing buildcraft as soon as I installed Immersive Intelligence, game was working just fine prior to installing the mod have no idea if its this mod thats causing it or the other one.
here's the crash report: 
[crash-2022-08-28_12.04.41-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/9440313/crash-2022-08-28_12.04.41-client.txt)

**Comment by Jazzofthesoul** [comment]
[crash-2023-07-22_17.55.19-client.txt](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/files/12136887/crash-2023-07-22_17.55.19-client.txt)
im having the same issue as soon as immersive intelligence was installed into the pack im using
