### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bones3951** [Team-Immersive-Intelligence/ImmersiveIntelligence#220]
**Describe the bug**
So I have tried compiling more up to date versions of this mod from the GitHub and I am doing this because of the manual crashing clients from my dedicated server; which I see has been fixed in a commit. I can run the mod fine within the testing environment (./gradlew runClient) but when I install the mod into a normal instance of the game I get the same error in the crashreport no matter what I do to mirror the configuration of the test environment. I am a total novice so any help is appreciated.

**To Reproduce**
1. Compile the mod from source
2. Add the immersiveintelligence-0.2.2(or higher).jar to a seprate 1.12.2 forge instance
3. Crash

**Expected behavior**
I expect the game to boot up just as it does within the test environment ./gradlew runClient

**Logs**
https://pastebin.com/VvPymKMV

**Environment**
 - OS: Linux Mint 19.3 Tricia x86_64
 - Minecraft version: 1.12.2
 - Forge version: I've tried latest and 2847 as the test environment uses
 - Immersive Intelligence version: compiled 0.22 (jan15), some points in commit history in between, 0.30
 - Immersive Engineering version: I've tried the latest 98, and 92

This project may very well be dead but I appreciate any help as the mod seems to be very cool.

**Comment by Pabilo8** [comment]
This may have been fixed, please check out and see if the error persists, so I can help you fix it or close the issue.
