### ISSUE TITLE
[BUG] Ammunition Workshop crash cause of rendering error

### ISSUE THREAD

**Issue by LeGrandCthulhu** [Team-Immersive-Intelligence/ImmersiveIntelligence#222]
**Describe the bug**
When using the Ammunition Workshop, the game crashes. 
When trying to use the projector, it shows a big black and purple texture around the wood slab block

**To Reproduce**
1. Assemble the Ammunition Workshop
2. Feed it basic casing filled with gunpowder and uranium core canister filled with HMX
3. Game crashes.

**Expected behavior**
Expected to produce the ammunition

**Screenshots or GIFs**
None

**Logs**
[crash-2022-12-30_02.14.56-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/10322725/crash-2022-12-30_02.14.56-client.txt)

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: Curseforge moddpack with forge 14.23.5.2858
 - Immersive Intelligence version: immersiveintelligence-0.2.1.jar
 - Immersive Engineering version: ImmersiveEngineering-0.12-98.jar
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

Other Mods :
- Chisel
- CoFH Core
- ConnectedTexturesMod
- Immersive Energy
- Immersive Petroleum
- Immersive Technology
- Iron Backpacks
- Iron Chests
- Just Enough Items (JEI)
- Just Enough Petroleum
- Just Enough Resources (JER)
- Redstone Flux
- Techguns
- Xaero's Minimap

**Comment by Pabilo8** [comment]
fixed by 178d3c2
