### ISSUE TITLE
[BUG] Minecraft crashing with rendering screen error

### ISSUE THREAD

**Issue by Playfra1** [Team-Immersive-Intelligence/ImmersiveIntelligence#223]
Hi there. Today I tried to install immersive intelligence & engineering for 1.12.2 but my game crashes consistently after about 2 minutes with a "rendering screen" error. Any help will be well appreciated. Also sorry for my poor english...!

**Steps to reproduce the behavior:**
Open Minecraft with Forge 1.12.2-14.23.5.2859.
Wait some minutes.

**Expected behavior**
The game runs fine.

**Logs**
[crash-2023-01-03_13.00.54-client.txt](https://github.com/Pabilo8/ImmersiveIntelligence/files/10336575/crash-2023-01-03_13.00.54-client.txt)

**Environment**
 - OS: Windows 11 Home 22H2
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2859
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-98

**Comment by Pabilo8** [comment]
Fixed.
