### ISSUE TITLE
[BUG] Game crashes after making a canister revolver shot

### ISSUE THREAD

**Issue by FatSassin** [Team-Immersive-Intelligence/ImmersiveIntelligence#224]
**Describe the bug**
If you try to make a revolver canister shot in the ammunition workshop, the game will crash, and the world will be un-enterable

**To Reproduce**
In the workshop, by a conveyor belt place a canister revolver shot (i used steel canister with 4 parts WP), and on the other belt place a vanilla bullet casing filled with gun powder
**Expected behavior**
Either a canister shot should be made, or nothing should haappen

**Logs**
[latest.log](https://github.com/Pabilo8/ImmersiveIntelligence/files/10369082/latest.log)

**Environment**
 - OS: Win 11
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2860
 - Immersive Intelligence version: 0.3.0
 - Immersive Engineering version: 0.12-98

**Comment by Pabilo8** [comment]
Fixed.
