### ISSUE TITLE
[Feature Request] Question, 1.18.2

### ISSUE THREAD

**Issue by alexnitaly** [Team-Immersive-Intelligence/ImmersiveIntelligence#228]
**Category**
If it doesn't match any of the categories
**Description**
Sorry, I just couldn't find anywhere to ask this, but, is this ever going to be updated to 1.18.2?

**Comment by Pabilo8** [comment]
Currently we're focused on making 1.12 feature complete. After all the features are in, we can work on porting.
If anyone is willing to port the mod, they're free to and will get our help in doing so.
