### ISSUE TITLE
[BUG] Light Engineer Armor recipe bugged

### ISSUE THREAD

**Issue by RileyChurch** [Team-Immersive-Intelligence/ImmersiveIntelligence#247]
**Describe the bug**
In order to craft Light Engineer Armor items, the steel and leather item have to have exact durability.

**Expected behavior**
With all required items I expected that I´d get an armor piece.

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2860
 - Immersive Intelligence version: 0.2.1
 - Immersive Engineering version: 0.12-92

**Comment by Pabilo8** [comment]
Fixed.
