### ISSUE TITLE
Ammunitions workshop is unpowerable [bug?]

### ISSUE THREAD

**Issue by epiktechno** [Team-Immersive-Intelligence/ImmersiveIntelligence#248]
As title states
unless i'm dumb and not doing something right, i cannot get the ammunitions workshop to be powered by anything

creative power sources don't work either

samething happens with projectile workshop, but it somehow works without a power source
meanwhile it's brother does nothing
it has the things needed to construct
(i inserted uranium shell core and naval mine shell)

**Comment by Pabilo8** [comment]
Likely fixed in a previous commit.
