### ISSUE TITLE
issue with mortar shells

### ISSUE THREAD

**Issue by TandemSaucer736** [Team-Immersive-Intelligence/ImmersiveIntelligence#249]
Hey guys, is there a possibility to make mortar shell in survival? I haven't found a way to do this anywhere.

**Comment by Pabilo8** [comment]
First create the mortar shell casing using a metal press mold and 3 aluminium plates.
Fill the shell with gunpowder using a Filler.
Then create a core using a Projectile Workshop and fill it with components using another Projectile Workshop with a Projectile Filler upgrade (optional).
After all is done, combine the casing and core in the Ammunition Workshop.
