### ISSUE TITLE
[BUG] Multiple IE manual bugs (Latest 0.3.0 from github)

### ISSUE THREAD

**Issue by IVsniper** [Team-Immersive-Intelligence/ImmersiveIntelligence#259]
**Describe the bug**
Missing IE manual pages like emplacement, radar, artillery howitzer, etc./broken pages

**To Reproduce**
1 - Open IE manual
2.1 - No pages like "Warfare"
2.2 - In pages like "Inserters" there is missing text
2.3 - Page "Electroinc components" results a crash (logs are attached)

**Expected behavior**
Pages to be visible and accessable

**Screenshots or GIFs**
~

**Logs**
[latest.log](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/files/12324384/latest.log)
[crash-2023-08-11_22.06.17-client.txt](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/files/12324386/crash-2023-08-11_22.06.17-client.txt)

**Environment**
 - OS: Win10 Pro 22H2
 - Minecraft version: 1.12.2
 - Forge version: 1.12.2-forge-14.23.5.2860
 - Immersive Intelligence version: latest 0.3.0 from github
 - Immersive Engineering version: 0.12-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.
~

**Comment by IVsniper** [comment]
By the way, if i'm spamming too much with reports, please notify me, i just want to help, but don't want to cause inconvenience. Thank you for understanding

**Comment by Pabilo8** [comment]
No worries, you're doing a good job reporting all this.
These manual pages are missing, because there's a big manual rework (both code-wise and in page contents) that's currently in progress. The old content is missing, because it's being moved by @RexBas07 to a new system.

The crash will be fixed soon.
