### ISSUE TITLE
[BUG]When the machine gun changes ammunition, the game will crash

### ISSUE THREAD

**Issue by ShadowXTTT** [Team-Immersive-Intelligence/ImmersiveIntelligence#261]
**Expected behavior**
When the machine gun changes ammunition, the game will crash

**Logs**
[crash-2023-08-13_16.48.37-server.txt](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/files/12329175/crash-2023-08-13_16.48.37-server.txt)

**Environment**
 - OS:Windows 11
 - Minecraft version:1.12.2
 - Forge version:14.23.5.2859
 - Immersive Intelligence version:
 - Immersive Engineering version:
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

**Comment by IVsniper** [comment]
I've reported that already, same error as mine (saying just in case)
