### ISSUE TITLE
[Bug]: Ammo ballistics crash

### ISSUE THREAD

**Issue by IVsniper** [Team-Immersive-Intelligence/ImmersiveIntelligence#272]
### Initial Check

- [x] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

When trying to see bullet's ballistic trajectory (ctrl) game crashes

### Side

Client

### Reproduction

1. Find a bullet
2. Hover your cursor over it while holding ctrl
3. Game crashes

### Expected Behaviour

Ballistics data to be displayed and no crashes

### Logs

https://mclo.gs/Z2PTeIW / https://mclo.gs/LQjGLze

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by IVsniper** [comment]
Still active in the latest build

**Comment by IVsniper** [comment]
Still present in "Curseforge 0.3.0" build

**Comment by VDeltaGabriel** [comment]
I cannot find it in my dev branch

**Comment by Pabilo8** [comment]
Fixed by d77cdc9
