### ISSUE TITLE
[Bug]: Artillery howitzer is uncontrollable

### ISSUE THREAD

**Issue by IVsniper** [Team-Immersive-Intelligence/ImmersiveIntelligence#276]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

After the new build artillery howitzer became uncotrollable. You cannot input any data to it through it's data connector

### Side

Client

### Reproduction

1. Build artillery howitzer
2. Input any data to it
3. It doesn't react

### Expected Behaviour

Expected Artillery howitzer to be cotrollable

### Logs

https://mclo.gs/RMeZk1a

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Caused by marking the port as DATA instead of DATA_INPUT, will be fixed soon.

**Comment by IVsniper** [comment]
Was fixed in "Curseforge 0.3.0" build
