### ISSUE TITLE
[Bug]: Radio Station range

### ISSUE THREAD

**Issue by Mikivan099** [Team-Immersive-Intelligence/ImmersiveIntelligence#278]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

Hi, I can't find information about the range of the radio station. Can you tell me?

### Side

Client, Server

### Reproduction

213

### Expected Behaviour

321

### Logs

213

### Other Evidence

123

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
It's 128 blocks in clear weather and 96 blocks during rain or snowfall (75%). We added the value to manual in the latest update, you can also find it in the config file.
