### ISSUE TITLE
[Bug]filler not working

### ISSUE THREAD

**Issue by Satsuguian** [Team-Immersive-Intelligence/ImmersiveIntelligence#279]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

when i try to put a mortar shell in the filler it doesnt work  how do i use the filler?

### Side

Client

### Reproduction

1. make a extractor conveyor belt connecting to the filler
2. place a chest with a  mortar shell in it

### Expected Behaviour

it should be filled!

### Operating System

MacOS

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by IVsniper** [comment]
Was fixed in "Curseforge 0.3.0" build
