### ISSUE TITLE
[Bug]: upgraded engineer light armor boots crash by ticking player

### ISSUE THREAD

**Issue by Travis1933** [Team-Immersive-Intelligence/ImmersiveIntelligence#280]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

Well it seems that when I use the light engineer armor with improved boots and go into the water it crashes with ticking player

### Side

Server

### Reproduction

1. Engineer light armor boots upgraded  
2. Touch water
3. Freeze
4. Crash and Ticking player Error

### Expected Behaviour

Well, nothing, it can crash randomly but it does so directly when I enter the water with the improved light engineer boots (the 3 improvements but even with 1 it seems that it still crashes)

### Logs

https://api.mclo.gs/1/raw/bLtzSGs

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.2.2 and older

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Fixed in 0.3.0 curseforge release
