### ISSUE TITLE
[Bug]: Scope issues in this mod

### ISSUE THREAD

**Issue by minebloxian334** [Team-Immersive-Intelligence/ImmersiveIntelligence#281]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

So I got this problem with the rendering or zooming issue with the scope where I try to zoom in but everything was all glitchy and it was a seizure fest (Also seizure warning when clicking on this video):

https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/83629994/5af0c3d9-1090-4d02-828f-73a5bc263b70

The issue is the mod surge all along

I will update this once I figure out what was causing this. Might help with fixing this issue for anyone else who might have this issue

### Side

Client

### Reproduction

1. Apply scope on the machine gun (Any or use the Periscope and doesn't matter about the render distance btw)
2. Feast your eyes

### Expected Behaviour

Expected behavior? Zoom from a very far distance. Have a nice day

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.2.2 and older

### Immersive Engineering Version

0.98

**Comment by minebloxian334** [comment]
Ok, so it turns out that it was surge... If the dev team can't fix this issue because it maybe on the mod surge's side then you guys can close this. But anyway have a nice day

**Comment by Pabilo8** [comment]
Yes, probably caused by an another mod's code. Check out if it still occurs on the 0.3.0 release, there were some improvements to zooming/scopes, but not sure if they fix this.

**Comment by minebloxian334** [comment]
Heya! I just checked and it seemed like the zoom/scope problem with surge has been fixed! Thank you and I hope you have a good day
