### ISSUE TITLE
[Bug]: Game crashes when cursor pointing at Phosphogranate MK.1 

### ISSUE THREAD

**Issue by Mayday4058** [Team-Immersive-Intelligence/ImmersiveIntelligence#282]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

When I point the cursor at the Phosphogranate MK.1 artillery shell, the game freezes for a second and crashes.

### Side

Client, Server

### Expected Behaviour

It is supposed to be an artillery shell, right? So, it is expected that it should probably be usable?

### Logs

https://mclo.gs/BKqPB5z

### Operating System

MacOS

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.2.2 and older

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Most likely fixed in 0.3.0, please check if it persists and close the issue if it doesn't.

**Comment by Pabilo8** [comment]
Fixed by 9584a79
