### ISSUE TITLE
[Bug]: AP bullets strange behavior

### ISSUE THREAD

**Issue by IVsniper** [Team-Immersive-Intelligence/ImmersiveIntelligence#284]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

It appears that AP bullets have infinite penetration, resulting in wierd behavior. Also, they don't disappear immediately after losing all kinetic energy, they disappear only after ~30s after being shot (Check attached videos)

### Side

Client

### Reproduction

1. Take any AP (armor-piercing) bullet
2. Fire it at any block
3. It will pass through it for ifinite amount of blocks
///-------------------------///
1. Take any AP bullet
2. Fire it at any entity
3. After hit, it will remain on ground for fixed time

### Expected Behaviour

Expected bullets to disappear after X blocks (Depends on speed/mass/etc), or after hitting the entity

### Logs

https://mclo.gs/KMBvS4z

### Other Evidence

- AP infinite penetration
https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/7d216774-d6e4-4c23-b9c5-8d208dd8e679

- AP delay before disappearing
https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/45400200/6b7e6949-e18b-4813-b995-fee2b87e5f72

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Will be fixed as a part of a major ammunition system (behaviour and values) rework
