### ISSUE TITLE
[Bug]: Game crashes when inspecting grenade with ctrl

### ISSUE THREAD

**Issue by oofergoofer** [Team-Immersive-Intelligence/ImmersiveIntelligence#294]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

Game crashes when attempting to view a pre-made grenade's ballistics

### Side

Client, Server

### Reproduction

1. Open creative menu
2. Choose any pre-made grenade
3. Press ctrl to view grenade's ballistics (any grenade works)

### Expected Behaviour

game shouldn't crash

### Logs

https://mclo.gs/megx9xi

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by IVsniper** [comment]
Same issue as #272

**Comment by Pabilo8** [comment]
Fixed by d77cdc9
