### ISSUE TITLE
[Bug]: Very bizarre rendering issue with Radio Tower

### ISSUE THREAD

**Issue by brisingraerowing** [Team-Immersive-Intelligence/ImmersiveIntelligence#297]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

Formed radio tower renders as a translucent solid color in world (renders correctly in manual).

![2024-02-02_09 37 49](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/250409/4648676f-1b04-4f3b-a76d-7b0ca9acb178)

I'm investigating the other mods in the pack to see what conflicts.

### Side

Client

### Reproduction

1. Build and Form radio tower

### Expected Behaviour

Radio tower renders

### Logs

N/A (Rendering issue)

### Other Evidence

Likely a mod conflict. Will test and report.

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by brisingraerowing** [comment]
OK, testing with just IE, II and Had Enough Items the radio tower renders broken in world and in the manual.

**Comment by VDeltaGabriel** [comment]
Can confirm that the translucent model is displayed in the manual, however when the radio tower is built it has the correct model. Did you go through both stages of building the radio tower?
1. Build the multiblock and use the hammer to form it.
2. Use the charged electric hammer to finish the build

**Comment by brisingraerowing** [comment]
I'll test again later. Currently fighting with a 1.19.2 pack that doesn't want to load a world.

**Comment by brisingraerowing** [comment]
So when I clicked a second time with the powered hammer, my game ended up freezing briefly, but the structure formed.
