### ISSUE TITLE
Surveillance Machines

### ISSUE THREAD

**Issue by Pabilo8** [Team-Immersive-Intelligence/ImmersiveIntelligence#3]
Some work for Choroman:

- [x] Radar Model
- [x] Infrared Observer Model
- [x] Periscope

**Comment by Choroman** [comment]
Bo za mało mi roboty już było tak?!?!?!?!!?!?


No dobra

**Comment by Pabilo8** [comment]
> Bo za mało mi roboty już było tak?!?!?!?!!?!?
> 
> No dobra
Ta jasne, wracaj do roboty stary leniu ^^

**Comment by Choroman** [comment]
lololololololo
zaalolgowałem się na montażu
lololololololo
(spokojnie to ja,i tak pamiętam żeby sięwylogować)
|\  /-\    |)
|/  |   |  |\
|\  \-/    | /

sob., 21 wrz 2019 o 15:29 Paweł Godlewski <notifications@github.com>
napisał(a):

**Comment by Pabilo8** [comment]
Kilka lat minęło, ale content jest.
