### ISSUE TITLE
[Bug]: Several Item Name Issues & other

### ISSUE THREAD

**Issue by rafaelantunes04** [Team-Immersive-Intelligence/ImmersiveIntelligence#304]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

MC version: 1.12.2
Forge version: 14.23.5.2859
Mod version: 0.3.0
Lang: English (US)

**Disclaimer**
Content here is written to improve the mod and refine it in some ways, since the mod with the right dedication and community has a bright future ahead.
Some of these might be feature, but i since i dont know i prefer sharing instead of this being unknown.
Im going to start a bit of topic with a slight off topic request since i cant select bug and ask for feature request (Only for refining mod).
Im know how to program, but i'm not very proficient in Java but with more effort into it i think i can solve this problem. I have a bit of spare time to try my best at Team Immersive Intelligence, so feel free to contact me if interested in an extra pair of hands, even if only for testing and opinion.

### Changes

**Drill Heads Change**
_Since i dont have tinkers installed, i think it becomes a bit weird for drill mining levels to be thinkers instead of vanilla's._

- Diamond-Tipped Iron Drill Head: Mining level is obsidian being obsidian becomes weird, _imo_ diamond becomes a better choice since it describes well what it can mine (the same as a diamond pickaxe)

- Diamond-Tipped Steel Drill Head & Tungsten Drill Head: Mining level is cobalt and as i told earlier, it becomes weird, if changed to diamond when tinkers isnt installed will make more sense.

- Diamond-Tipped Tungsten Drill Head: The same but with Manyullyn.

![imagem](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/35634474/ae3c7f6e-f343-4ee5-98ea-eaabefb57f0f)

**Add Jei support**
-As the title say, this could help in the case of someone is lost in trying to craft something, adding a better user experience.

### Bugs

Now on the actual name bug report (dont know if its feature or not):

**Artillery Shells**
- "Phosphorgranate mk.1", "Napalmgranate mk.1" and "Geburtsgtagsgranate mk.1: Names are exactly as written here for these artillery shells, and in the inventory tab they are separated from the other shells, after the mortar shells, becoming a bit weird.

![imagem](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/35634474/602cc425-c06c-4b42-94c5-dd5ecf60e895)

**Hand Grenades And Railgun Grenades** 
- "Chemhandgranate mk.1", "Sprenghandgranate mk.1", "Sprenghandgranate mk.2", "Stielhandgranate mk.1", "Phosphorhandgranate mk.1", "Feuerwerkhandgranate mk.1": Names are exactly as written here for these hand grenades, and goes the same for the inventory tab, being the last one separated from the other hand grenades.

- "Schienenkanone Chemgranate mk.1", "Schienenkanone  Sprenggranate mk.1": Names are exactly as written here for these railgun grenades.

![imagem](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/35634474/61d70b13-5046-497f-9574-09da3de86a6a)

**Bullets & related**
- "Flammpatrone mk.1", "Wolframpatrone mk.1" (revolver), "Markierungpatrone mk.1", "Sprengpatrone mk.1", "Wolframpatrone mk.1" (machinegun)", "Stahlpatrone mk.1", "Phosphorpatrone mk.1", "Uraniumpatrone mk.1": Names are exactly as written here for these bullets, and in the inventory tab the "Uraniumpatrone mk.1" is separated from the other bullets, by two magazines, becoming a bit weird.

- Magazines right after the bullets: This might be solved by correcting the names, but the magazines after the bullets referenced before have the same names of the bullets in the description, with some having bullet names i cant even find using Jei, such as "Limemarkierungpatrone", being completely unaware of how to make these.

![imagem](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/35634474/492ad65e-2434-4857-bab6-63815419fa8b)

**Misc**
- "Seemine mk.1": Name of the item as written here, and in the description two spaces in the "Fitted with**__**Brass Core".

- "Radio-Sprengstoff TNT mk.1": Name of the item as written here, and in the description two spaces in the "Fitted with**__**Brass Core".

- "Radio-Sprengstoff Phosphor mk.1": Name of the item as written here, and in the description two spaces in the "Fitted with**__**Brass Core".

- "Tellermine mk.1": Name of the item as written here, and in the description two spaces in the "Fitted with**__**Brass Core".

- "SD-Mine mk.1": Name of the item as written here, and in the description two spaces in the "Fitted with**__**Brass Core".

![imagem](https://github.com/Team-Immersive-Intelligence/ImmersiveIntelligence/assets/35634474/5ffc9cee-aab0-44ce-8942-ef76425b8c10)

PS: Hope this Issue might help the development of the mod in any kind of way.

### Side

Client

### Reproduction

MC version: 1.12.2
Forge version: 14.23.5.2859
Mod version: 0.3.0
Lang: English (US)

### Expected Behaviour

Have the correct names of the corresponding language.

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Thanks for the report, will address the points below:
- tipped drill mining levels - These mining level names are defined in IE's lang file, but were unused. If you want to change them you can edit the lang file (resourcepack) or use crafttweaker to overwrite the translations.
- II supports JEI in most of its production machines, 0.3.1 will also add JEI support for ammo production machines
- the colored bullets are intentionally not listed (so it doesn't flood the inventory); they all have a brass core and a tracer powder component colored red, yellow, blue or green and are repeated, so they fill the entire magazine
- never gave it too much thought, but as you've shown, the ammo order is weird at places, I'll make it more organised soon

**Comment by Pabilo8** [comment]
Items order was changed, bullet names now include a standard system for gun type and caliber.
