### ISSUE TITLE
[Bug]: Game keep crashing

### ISSUE THREAD

**Issue by sunduck6115-hash** [Team-Immersive-Intelligence/ImmersiveIntelligence#314]
### Initial Check

- [x] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

I'm having crash when i try to connect on my forge server. and may friend do so.
i wanna know why

### Side

Client

### Expected Behaviour

I had to connect server and play softly, but now i cant.

### Logs

https://pastebin.com/y3BxP1Py

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.0 (Recent Dev Build)

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Can you try removing the config files on server and client and check if it works? it may be due to some old value in there.

**Comment by sunduck6115-hash** [comment]
I tried delete config, both server and client but it wont work.

**Comment by Kamix13** [comment]
Did it work for you after you deleted immersive intelligence? I have the same exact issue, I can't enter any world or make any new one, just keeps crashing with the same exact crash report and reason.
