### ISSUE TITLE
[Bug]: Using a bucket on a chemical bath opens the GUI and adds/removes the fluid from the machine

### ISSUE THREAD

**Issue by fastdelaspeed** [Team-Immersive-Intelligence/ImmersiveIntelligence#327]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

When using a bucket on a chemical bath, the GUI will open AND the bucket contents will be dumped into the bath. If using an empty bucket, the GUI will open and the chemical bath contents (if filled) will be put into the bucket.

### Side

Client

### Reproduction

1. Make chemical bath
2. Right click on chemical bath with fluid bucket
3. Observe as GUI is opened and bucket contents are added to chemical bath

### Expected Behaviour

I expect that when using a bucket on the chemical bath, the GUI will never open. Alternatively, the GUI only opens when both the bucket and bath are empty.

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
Most likely related to client-server sync, it will be fixed through moving the ChemBath into new multiblock system.

**Comment by Avalon2106** [comment]
> Most likely related to client-server sync, it will be fixed through moving the ChemBath into new multiblock system.

Closing issue due to the message above
