### ISSUE TITLE
[Bug]: Missing Mortar Shells from new II Creative inventory

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#334]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

Exactly what title says.

### Side

Client

### Reproduction

1. Open the II creative inventory and switch to Warfare Tab and surf it full. 
2. Notice that there are no Mortar Shells included here

### Expected Behaviour

My sweet mortar shells should be put back again to my australian tabs!1!11!!1!!1111!1!1!1!!!!1!11! D:<

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@Pabilo8 want a new branch for this, or can I take care of it on Dev/Avalon/Main?

**Comment by Pabilo8** [comment]
make a new branch
