### ISSUE TITLE
[Bug]: "Concealed" effect doesn't wear off at all (unless you reenter the world)

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#340]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

LEA armor with Camo upgrade works... A bit unpredictable. To activate it, you should somehow position yourself among the leaves. But when you try to get out of them... The effect doesn't go (unless you reload the world, then it will wear off).

### Side

Client, Server

### Reproduction

1. Craft/Get LEA chestplate
2. Craft/Get Camo upgrade
3. Imply Camo to LEA chestplate
4. Get into tree leaves
5. Get out of them
6. Still stay invisible even when you're not surrounded by green photosynthetic leaves. (Unless you reload the world)

### Expected Behaviour

I guess the Camo system should be sort of reworked... Also when you get out of leaves, you should get visible again

### Other Evidence

![image](https://github.com/user-attachments/assets/16416b45-381e-4263-a107-d23e762bedbd)

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
behaves correctly for vines and grass, only issue is with leaf blocks, looking into it now
