### ISSUE TITLE
[Bug]: LEA Boots problems

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#342]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

There are three problems related to LEA boots with upgrade:
1. Flippers upgrade
When wearing LEA Boots with Flippers upgrade in water, you don't get a speed boost at all.
2. Snowrackets upgrade
When wearing LEA boots with snowrackers upgrade you enter ice, you get some sort of "laggy" boost
3. Internal springs upgrade
LEA boots with Internal Springs upgrade doesn't silence your steps at all. (But it does cut the fall damage! Hooray!)

### Side

Client, Server

### Reproduction

1. Get/Craft LEA boots and it's upgrades
2. Apply different upgrades to LEA boots
3. Touch ice/touch water/touch grass

### Expected Behaviour

1. Flippers should give you a speed boost underwater to move more freely
2. Snowrackets should make (at possibility) entrance to ice as "lagless" as possible
3. Internal springs should silence your steps completely

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@Pabilo8 do we just want fall damage negation to be the main aspect of this, and get rid of quiet steps?

**Comment by Pabilo8** [comment]
@Avalon2106 yep, that would be more useful (and easier to implement)
