### ISSUE TITLE
[Bug]: Exoskeleton leggings use energy while swimming but do not provide speed boost

### ISSUE THREAD

**Issue by fastdelaspeed** [Team-Immersive-Intelligence/ImmersiveIntelligence#344]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

While swimming, if the sprint key is pressed and exoskeleton leggings are enabled (On or Overdrive), energy from a capacitor backpack is used but no speed boost is given.

### Side

Client, Server

### Reproduction

1. Create LEA leggings with exoskeleton
2. Put on charged capacitor backpack
3. Go swim in a pool
4. Hold sprint while swimming
5. observe energy in capacitor backpack being used but no speed boost is gained

### Expected Behaviour

Either Exoskeleton leggings in water offer a speed boost in swimming, or no energy is used (up to you)

### Logs

N/A

### Other Evidence

N/A

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Going to close this for the reason that:
-The exoskeleton can give you a swimming boost if you sprint on a surface under water and float up. The unit is Moreso geared for speed on land. I have updated the manual to to state this.
-If you want a swimming speed boost, please refer to the flipper upgrades for the boots. 

regardless, thank you for your contribution to the engineers cause
