### ISSUE TITLE
[Bug]: You can't place mines in survival

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#345]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

📻Smaller Devices

### Description

Exactly what title says. When you place landmine, or tripmine, or radio explosive, they are absolutely invisible and when you approach them they just disappear. And the placement problem happens ONLY in survival mode (in creative mode it's fine). What's even more strange, is that naval mines don't have such a problem

### Side

Server

### Reproduction

1. Craft/Get mines/radio explosives
2. If not already, enter survival mode
3. Place the landmine, or radio mine, or tripmine

### Expected Behaviour

The mines should be placed normally as in creative

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
marking as closed, fixed in dev/pabilo/restructure
