### ISSUE TITLE
[Bug]: Explosions from projectiles or mines don't damage the player

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#346]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

📻Smaller Devices

### Description

Player doesn't get damaged by explosions by tnt/rdx/hmx filled projectiles or mines. But the other mobs do get damaged as supposed.
Also upon explosion, there are no particles despite having "Particles: All" in graphics settings.

### Side

Client, Server

### Reproduction

1. Get/Craft projectile or mine with TNT/RDX/HMX component
2. If not already, enter the survival mode
3. Fuse/activate the projectile/mine
4. Other mobs get damaged by it, but player? Nah, player is made from adamantium

### Expected Behaviour

Obviously the player should get damaged by explosions!

### Other Evidence

![image](https://github.com/user-attachments/assets/4728b72f-afaf-476b-99a8-adf1c430b45a)
![image](https://github.com/user-attachments/assets/e879a930-1b36-41ca-bcdb-c828c846c23f)
![image](https://github.com/user-attachments/assets/4bf059f2-1fbd-4866-a2c2-4f0a330da01b)

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
When mines are visable, (placed in creative, see issue #345) and they show up in the world, they do explosive damage. This issue stems from #345, and will be resolved when it is fixed
