### ISSUE TITLE
[Bug]: Odd behavior of Mine Detector

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#347]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧰Items

### Description

1. The mine detector is invisible from First Person Perspective if held in right hand
![image](https://github.com/user-attachments/assets/3c72aa47-1642-4e2e-9226-2bd4a07d6bec)
2. If held in left hand, the MD is positioned in a very weird way
![image](https://github.com/user-attachments/assets/0f3df019-8c62-432e-952b-e4faa399974b)
3. On landmines, Mine Detector works fine, but on trip mines it's a bit more weird. Also beeping depends on proximity of player to the mine than proximity of block the player is looking at as said in the manual.
4. The MD beeps only when the mine is in player's FOV. I dunno, I can't really explain Mine Detector's behavior correctly

### Side

Client

### Reproduction

1. Craft/Get Mine Detector
2. Do various things with it

### Expected Behaviour

1-2. The MD should be rendered correctly in both hands
3. Beeping on tripmines should work the same as on landmines
4. MD beeping should happen no matter if mine is in player's POV or not.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@Pabilo8 will this be fixed during the AMT migration for positioning?

**Comment by Pabilo8** [comment]
@Avalon2106 Sure, all graphical bugs will be fixed by it

**Comment by Avalon2106** [comment]
> @Avalon2106 Sure, all graphical bugs will be fixed by it

Nice. Should I tackle the behavior portion while im at it?

**Comment by Pabilo8** [comment]
Yep, would be great if you did that.

**Comment by Avalon2106** [comment]
tested behavior:
The mine detector will start making a beeping sound if you are looking at the ground (3x3 centered around the mine)
The closer the play is to the mine, assuming the previous condition has been met, the quicker the beeps will be.

this behavior happens for the tellermine and the tripmine, but not the naval mine (obviously)
