### ISSUE TITLE
[Bug]: Arithmetic Logic Machine GUI problems

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#351]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

When choosing an ItemStack as argument for Expression, the input fields are located slightly too low
![image](https://github.com/user-attachments/assets/27e87e87-5e3e-4109-9d8b-9d9cecbb52b0)

Variable selection window gets off the inventory, which in addition overlaps with area of JEI item list
![image](https://github.com/user-attachments/assets/1874a4f3-0f67-4660-8e49-f65c0ec87d1a)

When you insert a Circuit into ALM for the first time, the tab doesn't appear until I either reopen the ALM, OR remove one of the already inserted circuit, OR switch to other already existing circuit tab (including circuit selection tab)
![image](https://github.com/user-attachments/assets/b9052e46-93b2-488f-9358-4dafd9632f06)

When choosing an argument as variable, the type of it doesn't become into special type addressing the variable
![image](https://github.com/user-attachments/assets/a1c34ed8-3126-4ccf-98a4-5fb7e1e230f5)

When "variable window" is opened, the inventory and other ALM UI buttons are still active, including visual bugs of highlight and item icons overlaying
![image](https://github.com/user-attachments/assets/49fcddba-da0a-4eba-a6e1-c2f277dd5d37)

You can't choose "_" variable from "variable window" for conditional variable, only through arrows

When changing the output variable in Expression window you get sent back to page 0 (page where you choose the operation and condition value) + "Expression" gets changed to "Null"

### Side

Client

### Expected Behaviour

All of the above shouldn't be happening at all.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
TODO LIST:

- [x] Item stack as argument for expression
(Done by Fastdelaspeed in PR #430 Thank you!!)

- [x] Variable selection window gets off the inventory, which in addition overlaps with area of JEI item list

- [x] Refresh ALM circuit display thing

- [x] When choosing an argument as variable, the type of it doesn't become into special type addressing the variable

- [x] When "variable window" is opened, the inventory and other ALM UI buttons are still active, including visual bugs of highlight and item icons overlaying

**Comment by Avalon2106** [comment]
for the third task on the list, the circuits in the GUI update when put in normally, but not when they are shift clicked in. Should I try to make it so the shift click thing works?
@Pabilo8

**Comment by Avalon2106** [comment]
@LolscopeDev2022 What did you mean by "When choosing an argument as variable, the type of it doesn't become into special type addressing the variable"?
