### ISSUE TITLE
[Bug]: Chemical Dispencer HANGS Minecarft

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#353]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

📻Smaller Devices

### Description

It doesn't even crash it, IT HANGS IT.

Upon activating the Chem. Dispenser it starts "dispensing" textureless voxels for a second, then completely hangs minecraft. Because of that, unfortunately, I can't provide it with logs.
![image](https://github.com/user-attachments/assets/b82c5196-fa64-49d5-ba97-9af90136839b)

### Side

Client, Server

### Reproduction

1. Place Chem. Dispenser, power it with RF
2. Feed it with any liquid (I used Molten Metal from Tinkers Construct)
3. Give it redstone signal
4. Yay it wooooooooooooooooooooooooooooooooooooooooooooo- *Minecraft gets hanged*

### Expected Behaviour

Voxels should get it's textures and Chem. Dispenser should not hang the game

### Other Evidence

Additional render bug:

Chemical Dispenser and Fluid Inserter don't have visible energy/data ports
![image](https://github.com/user-attachments/assets/4350e558-11b9-47ed-a101-afbb8a35df2a)

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by fastdelaspeed** [comment]
This may be a Linux or video driver specific bug. I just tried this on my Windows 10 NVIDIA machine, and while Minecraft did not hang, my FPS dropped significantly. Normally MC runs at a capped 144fps but while the dispenser is running it dropped to about 100. Can confirm voxels were also untextured. Perhaps this device renderer still needs to be finished.

**Comment by Avalon2106** [comment]
> This may be a Linux or video driver specific bug. I just tried this on my Windows 10 NVIDIA machine, and while Minecraft did not hang, my FPS dropped significantly. Normally MC runs at a capped 144fps but while the dispenser is running it dropped to about 100. Can confirm voxels were also untextured. Perhaps this device renderer still needs to be finished.

I believe that this is an issue with the current implementation of how we handle "chemthrower" adjacent projectiles, as the issue comes up with the heavy flamer emplacement, along with hanses with throwers, and this as well. I will take a look into making the projectiles better

**Comment by Avalon2106** [comment]
fun fact with this one! Currently, in dev/avalon/main (also dev/main) no particles are dispensed! Along with no audio for this either. also lacks any connectors for data (no clue if the data even works) or redstone IE cables
@Pabilo8 are we going to rework this, or remove it for now?

**Comment by Avalon2106** [comment]
as it turns out there projectiles have hands, and are quite good at using them

**Comment by Avalon2106** [comment]
fixed the issue in branch #353, leaving the texture/particle work for later.
