### ISSUE TITLE
[Bug]: All Document Processing Circuit commands crash minecraft

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#356]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

Exactly what title says. The error is always the same

### Side

Server

### Expected Behaviour

NO CRASH PLEASE

### Logs

https://mclo.gs/kjRJHg7

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@Pabilo8 passing this over to you, as it pertains to the data system rework. If so, make sure to re-assign the task
