### ISSUE TITLE
[Bug]: Missing textures for Basic and Encryption Circuits for ALM

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#358]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

Exactly what title says.

### Side

Client

### Reproduction

Place Basic or Cryptographic circuit into ALM and see with a corner of eye the missing textures inside the ALM

### Expected Behaviour

Where are my textures???

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Closed with merge
