### ISSUE TITLE
[Bug]: Incorrect model for Data Buffer and other similar blocks

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#359]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

There are few model errors in Data Buffer and similar to it device blocks:
![image](https://github.com/user-attachments/assets/90544f89-6030-4940-aecc-8de673d282f5)

1. The bigger port on DB is too high by 1 voxel. 
2. Smaller port on DB is too high by 2 voxels. 
3. Redstone port (only on Small DB) has uneven/non-square shape

### Side

Client

### Expected Behaviour

The models should be remade to accomodate the location of Data Connectors

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Small data devices are going to be changed in 0.4.0 (new models) so a fix to this is not currently needed, as it will be deprecated. Marking as closed
