### ISSUE TITLE
[Bug]: Data Router outputs data at wrong side

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#361]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

I used the "East" side to output the Data Packet. But according to Xaero's Minimap, this side is actually West.
![image](https://github.com/user-attachments/assets/e0bd1683-ce4a-43e8-9fb0-7d71dd2c3118)

So, either Xaero's minimap is wrong or the East and West sides of Data Router are wrong. Very likely it's second.

Edit: As fastdelaspeed stated, the Top and Bottom sides are also swaped

### Side

Client, Server

### Expected Behaviour

~~East and West outputs should be swapped. That's it~~ Easier solution: Change the information about number-side relevation in the manual.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by fastdelaspeed** [comment]
I did my own testing, and I can confirm that East-West _and_ Top-Bottom are swapped, **but** North-South works as indicated in the manual. It may be much easier to change the manual text than the code itself. The text should say:

Bottom - 0, Top - 1, North - 2, South - 3, West - 4, East - 5.

**Comment by LolscopeDev2022** [comment]
> I did my own testing, and I can confirm that East-West _and_ Top-Bottom are swapped, **but** North-South works as indicated in the manual. It may be much easier to change the manual text than the code itself. The text should say:
> 
> Bottom - 0, Top - 1, North - 2, South - 3, West - 4, East - 5.

Also a possible solution. And yeah, maybe it would be simpler just to rewrite the manual than rewrite the code lol
