### ISSUE TITLE
[Bug]: Incorrect output of crate in Skycrate station

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#364]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

When the Skycrate station receives a crate, it outputs it in a wrong spot which makes connecting the multiblock into conveyor belt... Impossible?

### Side

Server

### Expected Behaviour

It should output the received crate in the right place just after the conveyor

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by fastdelaspeed** [comment]
Cannot replicate this with /dev/avalon/main branch. All orientations were tested including mirrors, with all directions of conveyor including covered conveyor. For reference, these are the inputs and outputs of the Skycrate station:
![Image](https://github.com/user-attachments/assets/f98273e5-b26a-4c07-b40a-8cfba1fae1c1)
What is the setup you used that experienced this bug?

**Comment by Avalon2106** [comment]
marking as complete as the issue no longer is present within the dev branches
