### ISSUE TITLE
[Bug]: Missing Skycrate related multiblocks names in IP projectors

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#366]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🔑Utility

### Description

Exactly what title says
![image](https://github.com/user-attachments/assets/41ba2f6d-31ad-41eb-b91c-d1ffc9a7c586)

### Side

Client

### Expected Behaviour

The IP Projector should show the names correctly

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Closed with Merge
