### ISSUE TITLE
[Bug]: Crate gets destroyed on the "dead end"

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#367]
### Initial Check

- [x] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

When the Crate traveling by ropes (aka sent by Skycrate Station) reaches a Skycrate Post that is not connected to other Post or Station, it drops only Skycrate frame but not the crate itself. (Or maybe it's not a bug but a feature, who knows)

### Side

Server

### Reproduction

1. Send crate by Skycrate Station
2. Make it reach a "dead end" Skycrate Post
3. Skycrate frame? Here. The crate itself? Went to 4th dimension.

### Expected Behaviour

Maybe it should drop the crate as well?

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Closed with merge
