### ISSUE TITLE
[Bug]: Mechanical pump doesn't work at all

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#378]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

📻Smaller Devices

### Description

I gave pump the access to water and a barrel to output the liquids. I gave it rotation power - no action. I gave it redstone - no action either.

### Side

Server

### Expected Behaviour

Mechanical Pump should pump out the liquids like the normal electric pump should do as well.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@LolscopeDev2022 what fluid were you trying to pump?
