### ISSUE TITLE
[Bug]: Misplaced Radar "locator" thing in unfinished state

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#383]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

Exactly what title says. Under "unfinished" I mean the state when the multiblock has "glassy" texture and needs to be clicked again with electric hammer to finish it.
![image](https://github.com/user-attachments/assets/2cfd7377-316d-4d21-a771-0f6cabacac8f)
Note: "Locator" is misplaced only in unfinished state. Once you build it again with electric hammer, the model gets into into normal state

### Side

Client

### Reproduction

1. Build a Radar multiblock
2. Press on wooden scaffolding with Electric Hammer only once

### Expected Behaviour

The "locator" should be placed in it's normal place.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Feature meant for a later release (0.4.0), not for current set of dev builds, marking as closed (for now)

**Comment by LolscopeDev2022** [comment]
> Feature meant for a later release (0.4.0), not for current set of dev builds, marking as closed (for now)

Wdym? I'm talking about the render of radar, not the actual features
