### ISSUE TITLE
[Bug]: Data Input Machine doesn't send the data packet when connected "closely" to other Data multiblock

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#387]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

EWTS. This is a bug because, as I remember, it was possible to send a data packet while having DIM and ALM connected "very closely" (basically without connectors and without any gaps in blocks)

### Side

Server

### Reproduction

1. Place DIM and Arithmetic Logic Machine or Ballistic Computer multiblocks very close that their data ports on blocks are "connected" without data connectors. 
2. Send the data packet
3. The neighbor data-processing multiblock doesn't get the data packet

### Expected Behaviour

The block-to-block connected multiblock should receive the data packet from DIM

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@Pabilo8 is this an intended behavior?
I assume the logic is that of how capacitors/ energy storage blocks can be put directly onto input ports on machines and that works.
Do we want the same logic for data, or will it be connector only?

**Comment by Pabilo8** [comment]
@Avalon2106 yes, data devices should be able to send and receive data from adjacent ones
