### ISSUE TITLE
[Bug]: Broken render of Packer's UI

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#396]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

The Packer's UI (only it's Item packing variation. Fluid/Energy variants of Packer don't have such issue) is a bit broken
![image](https://github.com/user-attachments/assets/43220087-ce36-4233-b213-812a23b3b8ba)

### Side

Client

### Reproduction

Open the Packer UI. The packer shouldn't have upgrades of "fluid" packer or "energy" packer

### Expected Behaviour

The UI obviously should be clear from a such artifact

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@LolscopeDev2022 What exactly about the UI is broken? I'm having a hard time figuring out what is

**Comment by Avalon2106** [comment]
Reviewed on the latest version of Dev-Avalon, was not able to re-create
Only a minor issue with the UI being slightly misaligned if the game window size changes, but the UI fixes when opened again.
Marking as Closed
