### ISSUE TITLE
[Bug]: You can't hold backspace when editing variable in DIM

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#400]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🔑Utility

### Description

EWTS. I should say that it happens at some very rare circumstances that I don't know how to track them. Though, sometimes it really happens that you can't hold backspace when editing value to erase text faster

### Side

Client

### Expected Behaviour

You should be able to hold backspace when editing the variable no matter what

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
@LolscopeDev2022 can you try to figure out what is causing this? It could be a OS keyboard/ "sticky keys" type issue rather than a software issue.

**Comment by Avalon2106** [comment]
Unable to replicate this issue. If it pops up again in the future, a deeper dive will be warranted
