### ISSUE TITLE
[Bug]: In Fuel Station UI, when it's full with a liquid, has some liquid texture coming off the "container"

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#403]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧊Rendering

### Description

EWTS.
![image](https://github.com/user-attachments/assets/76be59a5-294a-4cad-828b-156404e19163)

### Side

Client

### Expected Behaviour

When the FS is full, there shouldn't be any fuel texture coming off it

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Closed with merge
