### ISSUE TITLE
[Bug]: List of multiblocks that have problematic collision box

### ISSUE THREAD

**Issue by LolscopeDev2022** [Team-Immersive-Intelligence/ImmersiveIntelligence#405]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

I will split the list into two categories: "blocky" collision box (multiblocks that clearly copy CB of block structure before multiblock formation) and "irregular" collision box (multiblocks that have collision boxes in the wrong places)

Multiblocks with "blocky" collision box:
- Skycrate Post
- Skycrate Station
- Skycart Station
- Arithmetic Logic Machine
- Precision Assembler
- Redstone Data Interface
- Coagulator
- Radar
- Vulcanizer

Multiblocks with "irregular" collision box:
- Radio Tower (some of it's "steel rods" are offset)
![image](https://github.com/user-attachments/assets/188a0eaf-26a2-412c-8eaa-35c97a2e0fa9)
- Fuel Station (The canister with fuel has a bit too high collision box)
- All normal and Chain Fence Gates (First, they all have one weird redstone wire collision block in form of a block (no pun intended) even if Redstone Controll upgrade is not installed. Second, they all have two stray collision boxes 1 block tall and 1 voxel wide which can be seen if you hold an engineer's wrench)
![image](https://github.com/user-attachments/assets/215384dd-1a9d-493d-942e-b2bf2b284872)

### Side

Server

### Reproduction

Just check the collision boxes of the multiblocks

### Expected Behaviour

The collision box of the multiblocks should be edited and fixed

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Pabilo8** [comment]
@Avalon2106 Yep, it will
