### ISSUE TITLE
[Bug]: Chain Gates have no sound when opening and closing

### ISSUE THREAD

**Issue by meowkitty9694e** [Team-Immersive-Intelligence/ImmersiveIntelligence#416]
### Initial Check

- [X] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

When opening or closing a II fence gate (doesn't matter what one), sound effects don't play for opening and closing them. It also spits this into the log once.
![image](https://github.com/user-attachments/assets/7ff775fe-1709-43e0-8912-fd09739b6759)

### Side

Client

### Reproduction

1. Build and activate a fence gate multiblock (doesn't matter which)
2. Right click it.
3. It doesn't produce any noise.

### Expected Behaviour

Sound should play when opening or closing it.

### Operating System

Linux

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
closed with merge
