### ISSUE TITLE
[Bug]: intelligence tab in Engineer's Manual doesnt open,also some structures and features like skycrate or belts dont appear in The manual as well

### ISSUE THREAD

**Issue by Dididi225656** [Team-Immersive-Intelligence/ImmersiveIntelligence#419]
### Initial Check

- [x] I have checked the existing issues and this one is not a duplicate

### Category

🧱Multiblocks

### Description

The Engineer's Manual appear to be Buggy, because some of The coolest part of Imm Intel is The Rotary device, and everything in The Rotary device category seems glitched, like skycrate and The belts.

I dont know Its because i play on T-Launcher but i had no choice, my countrie inflation is huge :/

### Side

Client

### Reproduction

1. Open the manual
2. Click "Intelligence"
3. Wait
4. Omg,It did nothing

### Expected Behaviour

The manual dont show things that are in The game

### Operating System

Windows 10 or newer

### Minecraft Version

1.12.2

### Immersive Intelligence Version

0.3.1-dev2

### Immersive Engineering Version

0.98

**Comment by Avalon2106** [comment]
Issue was fixed, not yet pushed out with the next dev release
