### ISSUE TITLE
[Feature Request] Location tracer for howitzer.

### ISSUE THREAD

**Issue by Carvercarver1** [Team-Immersive-Intelligence/ImmersiveIntelligence#43]
Advanced finding method for ballistic computer-driven howitzer coordinates. Since it uses "how far from the howitzer's position it is" instead of world coordinates atm (unless radar comes up, with pin pointing the location by clicking on the chunk), it will be good idea to add a tool which, when linked to that howitzer, show coordinates for the howitzer, e.g how far on xyz coordinates that location is. Probably can use the same method of binoculars do. In return this may cost some more resources to make. Perhaps even small multiblock for targeting laser.

**Comment by Carvercarver1** [comment]
New thought: a tracking shell? Expensive, but allows for target calculation without need to go to the bombing zone on foot (real world tactic is aplicable: one shell is too close, one too far, and the middle ground is the main targeting). Maybe just displays world coordinates where it landed. 
As well as showcase a flying path if flew via particles, when you hold binoculars?

**Comment by Pabilo8** [comment]
Now that we have IR Observers, we can track the entity till its last position. No guided shells though.
