### ISSUE TITLE
[Feature Request] More documentation

### ISSUE THREAD

**Issue by aaronhsmine** [Team-Immersive-Intelligence/ImmersiveIntelligence#59]
**Category**
**Basically every Category**
**Description**
There's currently very little documentation about this mod on the internet, and the in-game documentation isn't very helpful either (page 3 of the Engineer's Manual for the Data Input Machine doesn't even contain any documentation, just "data_input_machine2"). Although the concept of the Data System seems interesting, i couldn't manage to control the howitzer with it (yet). Maybe create a GitHub wiki?

**Comment by aaronhsmine** [comment]
Note about getting the artillery to work: I just found your YouTube video about it, and it turns out the in-game manual for the howitzer is wrong (it states that variable "m" is for sending an action, although it is "c").

**Comment by ChilledDayz** [comment]
Do you have a link for the YouTube video please.

**Comment by aaronhsmine** [comment]
Sure: 
https://www.youtube.com/watch?v=o3mt9exEfL0

**Comment by Pabilo8** [comment]
A new manual variable display has been added in https://github.com/Pabilo8/ImmersiveIntelligence/commit/ba7232a5bd93e7fe9d6e75fd08f0b86e6c1ff657

I'm not sure if the mod should have an external wiki, each machine has a manual page already and that's enough to use the mod. I'm going to make some youtube videos for the data-related machines, but also hoping someone would make a tutorial series for it.
