### ISSUE TITLE
[BUG] Translucent Block/Multiblock glitch

### ISSUE THREAD

**Issue by Mushguys** [Team-Immersive-Intelligence/ImmersiveIntelligence#76]
**Describe the bug**
If you place a Programmable Speaker, leave it for a while, then come back to it, it will be translucent white.
~~Also, anything connected to it by data wire is translucent too.~~
The block is also visible, even beyond the fog distance, as long as its chunk is loaded.

**Edit:** It's not just the Speaker. Other things from II are doing it too. But nothing from IE.
**Edit 2:** Motor Belts are doing it too.
**Edit 3:** It's not by data network. The objects just happened to all go translucent at once. Might be a chunk thing.

**To Reproduce**
1. Place a Programmable Speaker
2. Leave for a while, then come back.
3. Programmable Speaker, ~~and anything connected by data,~~ is translucent.

**Expected behavior**
Programmable Speaker stays solid, the way it looks in the inventory.

**Screenshots or GIFs**
Translucent Speaker
![2020-07-12_16 44 19](https://user-images.githubusercontent.com/67520825/87318231-956ba180-c517-11ea-818a-9659fc9bfa29.png)
Translucent Speaker and Data Input Machine
![2020-07-12_16 12 04](https://user-images.githubusercontent.com/67520825/87318228-94d30b00-c517-11ea-837b-1eae07234976.png)
Translucent Speaker beyond fog distance
![2020-07-12_16 45 21](https://user-images.githubusercontent.com/67520825/87318232-956ba180-c517-11ea-9652-bbeafc6bd3a1.png)
Translucent Precision Assembler
![2020-07-13_16 19 27](https://user-images.githubusercontent.com/67520825/87328372-e930b780-c524-11ea-9766-4f8211d9f8d8.png)
I caught Motor Belts doing it too (but only from this particular angle)
![2020-07-18_14 16 02](https://user-images.githubusercontent.com/67520825/87854432-8151e680-c901-11ea-9189-2e3d586f9911.png)

**Environment**
 - OS: Linux Debian 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2847
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-89
No other mods installed.

**Comment by Pabilo8** [comment]
This was one of the flaws of the old TMT renderer, with AMT it's no longer present.
