### ISSUE TITLE
[BUG] Can't combine torque of 2 machines with wooden gearbox

### ISSUE THREAD

**Issue by SomeRandomPetey** [Team-Immersive-Intelligence/ImmersiveIntelligence#84]
**Describe the bug**
When trying to combine torque from 2 windmills with a gearbox, the torque will not add the two torque values.

**To Reproduce**
1. Place a gearbox
2. Connect 1 wheel to it that is connected to a windmill (have not tested it with water wheels yet)
3. Torque will be at 8 if gears are placed in
4. Add another windmill
5. Torque will stay at 8

**Expected behavior**
Torque will increase to 16

**Screenshots or GIFs**
![2020-10-07_09 23 29](https://user-images.githubusercontent.com/42192920/95336791-0f919500-087f-11eb-8c49-0211acc99d0c.png)
![2020-10-07_09 23 36](https://user-images.githubusercontent.com/42192920/95336792-102a2b80-087f-11eb-8bfb-4e7f69b0db47.png)

**Logs**
Nothing in the latest.log about II or IE

**Environment**
 - OS: Windows 10 Home build 18362.1082
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-98
If you have other mods installed, it would be nice if you send a list of them too (maybe it's not II's fault after all) ^^.

(Modlist)
Project Red - Fabrication (by MrTJP)
Track API (by cam72cam)
MrTJPCore (by MrTJP)
Resource Reloader (by LatvianModder)
Ding (by ohaiiChun)
Project Red - Integration (by MrTJP)
Project Red - Lighting (by MrTJP)
Project Red - Mechanical (by MrTJP)
Integrated Tunnels (by kroeser)
Project Red - World (by MrTJP)
Project Red - Compat (by MrTJP)
Mantle (by mDiyo)
VanillaTweaks (by StrikerRocker)
Tech Reborn (by modmuss50)
Overloaded Armor Bar (by tfarecnim)
BdLib (by bdew)
VanillaFix (by Runemoro)
Modular Diversity (by BordListian)
B.A.S.E (by lanse505)
AttributeFix (by DarkhaxDev)
Open Modular Turrets (by Keridos)
TellMe (by masady)
QMD (by lach_01298)
Common Capabilities (by kroeser)
AutoRegLib (by Vazkii)
CraftTweaker (by Jaredlll08)
Brandon's Core (by brandon3055)
Immersive Petroleum (by Flaxbeard)
Pollutant Pump (by bright_spark)
Controlling (by Jaredlll08)
AE2 Wireless Fluid Terminal (by TheRealp455w0rd)
AE2 Wireless Terminal Library (by TheRealp455w0rd)
Advanced Chimneys (by EnderLanky)
Enchantment Descriptions (by DarkhaxDev)
ForgeEndertech (by EnderLanky)
Advanced Generators (by bdew)
ExtraCells2 (by Destroyer7128)
Blur (by tterrag1098)
Engineer's Tools (by wilechaote)
TOP Addons (by DrManganese)
ContentTweaker (by Jaredlll08)
Integrated Crafting (by kroeser)
Magneticraft (by cout970)
Custom Backgrounds (by Lumien231)
Alternating Flux (by AntiBlueQuirk)
Just Enough Items (JEI) (by mezz)
Immersive Intelligence (by Pabilo8)
GunpowderLib (by Jackyy)
Baubles (by Azanor13)
Gas Conduits (by pupnewfster)
MoreTweaker (by noeppinoeppi)
Foam​Fix (by asiekierka)
PneumaticCraft: Repressurized (by desht_08)
MMDLib (by MCModDev)
WrapUp (by TheLMiffy1111)
Better Animal Models (by cybercat5555)
Bedrock B Gone (by Karjah)
Sonar Core (by sonar_sonic)
Gamestage Books (by IterationFunk)
MCMultiPart (by amadornes)
Applied Energistics 2 (by AlgorithmX2)
Chameleon (by Texelsaur)
Natura (by mDiyo)
Forge MultiPart CBE (by covers1624)
MultiBlock Stages (by Sky_Som)
Cyclops Core (by kroeser)
CodeChicken Lib 1.8.+ (by covers1624)
In Control! (by McJty)
Storage Drawers (by Texelsaur)
It's the little things (by Zlepper)
Better Burning (by DarkhaxDev)
Epic Siege Mod (by Funwayguy)
Redstone Flux (by TeamCoFH)
Just Enough Resources (JER) (by way2muchnoise)
Modular Machinery (by HellFirePvP)
Shadowfacts' Forgelin (by ShadowfactsDev)
Mekanism (by bradyaidanc)
Mekanism Generators (by bradyaidanc)
Mekanism Tools (by bradyaidanc)
Industrial Renewal (by CassioKF)
AcademyCraft (by weathfold)
Cosmetic Armor Reworked (by LainMI)
Deep Mob Learning (by IterationFunk)
Futurepack Mod (by Mcenderdragon)
Actually Additions (by Ellpeck)
Traveler's Backpack (by Tiviacz1337)
Ender Storage 1.8.+ (by covers1624)
Ender Tweaker (by Shadows_of_Fire)
Practical Logistics 2 (by sonar_sonic)
p455w0rd's Library (by TheRealp455w0rd)
Better With Lib (BWM - Core) (by primetoxinz)
Wireless Pattern Terminal (by TheRealp455w0rd)
Game Stages (by DarkhaxDev)
AE2 Wireless Interface Terminal (by TheRealp455w0rd)
Sound Reloader (by TheWhoAreYouPerson)
The One Probe (by McJty)
Thermal Foundation (by TeamCoFH)
WanionLib (by WanionCane)
RealBench (by Prototik)
ArchitectureCraft - TridentMC Version (by darkevilmac)
Integrated Dynamics (by kroeser)
KleeSlabs (by BlayTheNinth)
OreLib (by OreCruncher)
Better With Engineering (by primetoxinz)
ConnectedTexturesMod (by tterrag1098)
ModelLoader (by cout970)
EnderCore (by tterrag1098)
Bookshelf (by DarkhaxDev)
Morph-o-Tool (by Vazkii)
Industrial Foregoing (by Buuz135)
AE2 Stuff (by bdew)
NuclearCraft: Overhauled (by tomdodd4598)
Gauges and Switches (by wilechaote)
Bloodmoon (by Lumien231)
Ore Excavation (by Funwayguy)
Thermal Dynamics (by TeamCoFH)
Techguns (by pWn3d_1337)
FastWorkbench (by Shadows_of_Fire)
Engineer's Doors (by nihiltres)
Chisel (by tterrag1098)
Patchouli (by Vazkii)
ReWIRED (by mallrat208)
Immersive Railroading (by cam72cam)
Farseek (by delvr)
Quark (by Vazkii)
Immersive Engineering (by BluSunrize)
SwingThroughGrass (by exidex)
UniDict (by WanionCane)
Immersive Posts (by TwistedGate)
MTLib (by Jaredlll08)
A Lib (by al132)
Custom Main Menu (by Lumien231)
Open Modular Passive Defense (by Keridos)
OMLib (by Keridos)
Robotic Parts (by Aun_Sar)
Pollution of the Realms (by EnderLanky)
RandomPatches (by TheRandomLabs)
Streams (by delvr)
Inventory Tweaks (by JimeoWan)
AppleSkin (by squeek502)
Resource Loader (by Lumien231)
Compact Machines (by davenonymous)
Mod Name Tooltip (by mezz)
Better Questing - Quest Book (by Drethic)
Project Red - Base (by MrTJP)
Multi Mob Library (by Daveyx0)
Better Animals Plus (by cybercat5555)
Immersive Technology (by tgstyle0)
BetterNether (by paulevs)
MixinBootstrap (by LX_Gaming)
Fast Leaf Decay (by olafskiii)
Mouse Tweaks (by YaLTeR)
BetterFps (by Guichaguri)
ReAuth (by TechnicianLP)
CreativeCore (by CreativeMD)
ModTweaker (by Jaredlll08)
LittleTiles (by CreativeMD)
Ender IO (by CrazyPants_MC)
LLibrary (by _ForgeUser11902522)
Integration Foregoing (by Jackyy)
Clumps (by Jaredlll08)
Primitive Mobs (by Daveyx0)
Better Questing (by Funwayguy)
Better Questing - Standard Expansion (by Funwayguy)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
MMD OreSpawn (by jriwanek)
Morpheus (by Quetzi)
Chisels & Bits (by AlgorithmX2)
JourneyMap (by techbrew)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
Matter Overdrive: Legacy Edition (by hrznstudio)
Better With Mods (by primetoxinz)
Integrated Terminals (by kroeser)
CoFH Core (by TeamCoFH)
Thermal Expansion (by TeamCoFH)
Phosphor (Forge) (by jellysquid_)
Placebo (by Shadows_of_Fire)
Tesla Core Lib (by face_of_cat)
FPS Reducer (by bre2el)
Wireless Crafting Terminal (by TheRealp455w0rd)
CoFH World (by TeamCoFH)
Squeedometer (by squeek502)
Squake (by squeek502)
Better Advancements (by way2muchnoise)
Project Intelligence (by brandon3055)
More Overlays (by FeldiM245)
JAOPCA (by TheLMiffy1111)
Champions (by TheIllusiveC4)
Reborn Core (by modmuss50)
Engineer's Decor (by wilechaote)

**Comment by Hawk777** [comment]
The speeds need to be *exactly* the same. The only way I ever got it to work was to use two identical power sources (two waterwheels with flowing water touching exactly the same blocks on each) and exactly the same lengths of belt from the power sources to the gearbox. Annoying enough that I’m just not going to use the rotary stuff personally, but if you really want it, maybe this will help.

**Comment by Pabilo8** [comment]
Fixed by 4b849e1
