### ISSUE TITLE
[BUG] Infrared Binoculars max out at 10x

### ISSUE THREAD

**Issue by Smearfo** [Team-Immersive-Intelligence/ImmersiveIntelligence#85]
**Describe the bug**
While the infrared binoculars show that they can zoom up to 20x, the actual zoom distance of them maxes out at 10x,

**To Reproduce**
Equip infrared binoculars and attempt to zoom in all the way, instead of going all the way to 20x, the screen stops zooming in at 10x.

**Expected behavior**
When using infrared binoculars, one should be able to zoom in all the way to the intended maximum of 20x

**Screenshots or GIFs**
![IIBinoculars](https://user-images.githubusercontent.com/46880050/95387617-fb6d8800-08be-11eb-9d31-c49cac99afa7.gif)

**Environment**
 - OS: Windows 10
 - Minecraft version: 1.12.2
 - Forge version: 14.23.5.2854
 - Immersive Intelligence version: 0.1.1
 - Immersive Engineering version: 0.12-98
 - No other mods installed

**Comment by Pabilo8** [comment]
Fixed.
